<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__cena_yslugi_filiala</name>
   <tag></tag>
   <elementGuidId>93363fdd-7861-425d-8b00-6a50497ac5b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#5JyJm0L7iLMdRECaydLmL</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div/label/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>56ba163d-d4bb-4c0c-b604-05d9fc31a742</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>5JyJm0L7iLMdRECaydLmL</value>
      <webElementGuid>1bb69186-a0c7-4317-a892-9155ea75939c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_input__Xf-yT</value>
      <webElementGuid>56c60e65-165f-4e5b-97ed-b50dc246ed0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5a8d2e59-ba1a-4414-b632-19fec7cc35f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a09159b7-68a4-4512-b5e6-e6b60d247443</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;5JyJm0L7iLMdRECaydLmL&quot;)</value>
      <webElementGuid>32730cfc-7da7-4768-845d-f08d2114050d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='5JyJm0L7iLMdRECaydLmL']</value>
      <webElementGuid>12a4b73a-0c33-44b2-af29-257d123a2d25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/label/input</value>
      <webElementGuid>229f6d38-cb1c-4db7-a281-b28624c01743</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '5JyJm0L7iLMdRECaydLmL']</value>
      <webElementGuid>460f4589-6d51-42a8-838b-d4f50c46ab40</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
