<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__dlitelnost_yslugi_filiala</name>
   <tag></tag>
   <elementGuidId>d0fc34b1-543d-4f2d-847b-c48ec78df322</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#1jkCoprQiFLjhwZKuGKiK</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div/div/div/label/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>af38146c-b456-45e4-a0ff-dbd668942c3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>1jkCoprQiFLjhwZKuGKiK</value>
      <webElementGuid>acb67500-3cb7-4464-ac52-17b36df51ffe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_input__Xf-yT</value>
      <webElementGuid>5188767f-6b3f-4809-bc01-4691d8511ed4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>69a8cab1-e0e1-4d05-bad1-319ee24c135d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>9b262d4b-bce2-4901-8ac1-a67cb88287cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1jkCoprQiFLjhwZKuGKiK&quot;)</value>
      <webElementGuid>68d3fa3b-13b6-4ba2-8c88-289e92e4d86f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='1jkCoprQiFLjhwZKuGKiK']</value>
      <webElementGuid>63d011b2-281b-4b84-b3b1-95b445cd5ab7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/label/input</value>
      <webElementGuid>b3ee5899-6c15-4cb4-9a10-21a45afb2452</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '1jkCoprQiFLjhwZKuGKiK']</value>
      <webElementGuid>802e8972-ddac-415c-ac75-de7edde3cefc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
