<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_search_yslugi_filiala</name>
   <tag></tag>
   <elementGuidId>a47af224-6b85-4809-8238-a21d399b9a8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[type=&quot;search&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class, 'style_searchInput')]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c0c03ec8-6ab3-4360-9670-5f0e0f9e43be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>bf75b33d-e770-4b35-a626-4d40e05b0b95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Поиск</value>
      <webElementGuid>fd0dae6f-e68e-4a5d-a15c-047d593e9e59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Q</value>
      <webElementGuid>e9cbb4ee-a9b0-4104-b3b0-0e26f6bd34ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;styles_layout__wrapper__2zeB1&quot;]/div[@class=&quot;styles_layout__container__3D3Vr styles_layout__container_admin__2X_qx&quot;]/main[@class=&quot;styles_layout__content__1BAJN styles_layout__content_admin__WVT00&quot;]/section[@class=&quot;styles_contentLayout__1rqiW&quot;]/div[@class=&quot;styles_container__1bWbk&quot;]/div[@class=&quot;styles_container__2d1pT&quot;]/div[@class=&quot;content__container&quot;]/div[1]/div[@class=&quot;style_searcherWrapper__2AM9Y&quot;]/div[@class=&quot;style_searchContainer__2NR0t&quot;]/div[@class=&quot;style_searchInput__3iwOf&quot;]/input[1]</value>
      <webElementGuid>5d65dc04-402c-4ea2-a922-be307557de0b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Q']</value>
      <webElementGuid>d8d3b0e6-55a4-4d73-841e-7a6826363300</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/main/section/div/div[3]/div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>90bed6a7-0f06-4280-aa8e-d6e7789f89da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>05ba5c52-a7c9-49b5-98cf-2ffbdef55464</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @placeholder = 'Поиск']</value>
      <webElementGuid>ff198336-7cdc-433f-83ef-071910c14297</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
