<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_search_in_page_vrach</name>
   <tag></tag>
   <elementGuidId>ec8b6934-2f03-4505-8d04-1561bb3b270a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type = 'search' and @placeholder = 'Поиск']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[type=&quot;search&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e4055eb8-990e-42df-b329-720acf7e53e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>447a0407-d628-4089-89c4-9f5b8e2bad5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Поиск</value>
      <webElementGuid>1bcfb581-3ada-4edc-bbdf-44d9984deb85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Б</value>
      <webElementGuid>2ace9606-fa7c-40ce-8a4f-a6435c645811</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;styles_layout__wrapper__2zeB1&quot;]/div[@class=&quot;styles_layout__container__3D3Vr styles_layout__container_admin__2X_qx&quot;]/main[@class=&quot;styles_layout__content__1BAJN styles_layout__content_admin__WVT00&quot;]/section[@class=&quot;styles_contentLayout__1rqiW&quot;]/div[@class=&quot;styles_container__1PndP&quot;]/div[@class=&quot;styles_actions__container__3EKRJ&quot;]/div[@class=&quot;styles_input__container__17EaL&quot;]/div[@class=&quot;style_searcherWrapper__2AM9Y styles_searchInput__gaHa6&quot;]/div[@class=&quot;style_searchContainer__2NR0t&quot;]/div[@class=&quot;style_searchInput__3iwOf&quot;]/input[1]</value>
      <webElementGuid>df2e62c5-14a4-4e72-8aec-12ac3a01fd30</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Б']</value>
      <webElementGuid>51514eb0-b695-4db6-afce-bd654b1624f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/main/section/div/div[2]/div[3]/div[2]/div/div[2]/input</value>
      <webElementGuid>007bd3b6-5fd6-4112-bfef-b20bf44e591c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>6db901ef-d8c0-40ba-b685-6c2594249bcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @placeholder = 'Поиск']</value>
      <webElementGuid>b9fecb54-6e20-4e19-8586-8b5aae0e3a4f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
