<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>profile_vrach_in_page_vrach_kliniki</name>
   <tag></tag>
   <elementGuidId>a82873b0-b400-4773-b668-dd9626c5f964</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.ant-popover-open</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '${GlobalVariable.Test_vrach_full}' or . = '${GlobalVariable.Test_vrach_full}')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[text() = 'Боевая Машина Магович']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1fb58966-9a87-4820-9cce-22c094ba4b6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-popover-open</value>
      <webElementGuid>e289806f-b64e-489e-ada0-31ea9ea2dabe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>${GlobalVariable.Test_vrach_full}</value>
      <webElementGuid>158249ce-a15b-4e30-a4a3-0985a20f4543</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;styles_layout__wrapper__2zeB1&quot;]/div[@class=&quot;styles_layout__container__3D3Vr styles_layout__container_admin__2X_qx&quot;]/main[@class=&quot;styles_layout__content__1BAJN styles_layout__content_admin__WVT00&quot;]/section[@class=&quot;styles_contentLayout__1rqiW&quot;]/div[@class=&quot;styles_container__1PndP&quot;]/div[@class=&quot;styles_table__wrapper__3VcQm&quot;]/div[@class=&quot;styles_table__row__5Gwmm&quot;]/span[@class=&quot;styles_table__row__item-shortened__1yU3K&quot;]/a[1]/span[@class=&quot;ant-popover-open&quot;]</value>
      <webElementGuid>e5766c99-2573-4a75-a76d-97cae920a917</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/main/section/div/div[3]/div[2]/span/a/span</value>
      <webElementGuid>ea0e263e-0070-4a30-b392-103070e68143</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Статус'])[1]/following::span[2]</value>
      <webElementGuid>c18cbc73-6f18-4c6a-b972-3b65afd7122d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Контактные данные'])[1]/following::span[3]</value>
      <webElementGuid>c6dfcc87-12ca-4d63-8789-19084d98c733</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Акушер-гинеколог'])[1]/preceding::span[1]</value>
      <webElementGuid>5f54ce02-f25f-4d4e-9358-229e7016c769</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Андролог'])[1]/preceding::span[2]</value>
      <webElementGuid>687709df-768f-4620-af5d-996215f444ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Боевая Машина Магович']/parent::*</value>
      <webElementGuid>dad166ce-1bc7-4b93-ad4f-a7da2f0a30db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/a/span</value>
      <webElementGuid>97c016be-1a9f-423c-9bdb-03f49d034b10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Боевая Машина Магович' or . = 'Боевая Машина Магович')]</value>
      <webElementGuid>81415b78-4a92-4ff8-a9a4-6569a0ed93ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
