<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>add_ysluga_two</name>
   <tag></tag>
   <elementGuidId>dcf7b766-6f29-4f4d-807e-1b5adf7da748</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id = 'react-select-10-option-1' and (text() = 'Тестовая услуга два' or . = 'Тестовая услуга два')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#react-select-10-option-1</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Первчиный приём' or . = 'Первчиный приём')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>024be5e7-f04d-478b-a2e5-7d22c772fd26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> css-1yxc0mn-option</value>
      <webElementGuid>620cf75c-f0b0-4a8b-92ba-2a769c9c4510</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-10-option-1</value>
      <webElementGuid>68a32c4b-61f9-426d-bbab-ed04d719955d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>87f6fe98-b7a0-4aad-9a67-95d4f084931e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Тестовая услуга два</value>
      <webElementGuid>d2950719-155a-4613-9512-9eef02c311fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-10-option-1&quot;)</value>
      <webElementGuid>75a8dc98-7856-47d9-b8f4-5d0303c4b3d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-10-option-1']</value>
      <webElementGuid>f58cd9a3-5f40-4d9f-8d83-13e4eac65022</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='drawer']/div/div/div/form/div/div[5]/div/div/div/div/div/div[2]/div/div[2]</value>
      <webElementGuid>0a054693-4349-424b-9cb8-667e45535603</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Тестовая услуга'])[1]/following::div[1]</value>
      <webElementGuid>9a60985b-6f8c-477d-9660-a2a14a8ce0a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Добавить услугу'])[1]/following::div[9]</value>
      <webElementGuid>0744a534-a671-493b-bd18-8c974173495c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Повторный приём'])[1]/preceding::div[1]</value>
      <webElementGuid>acefc916-c411-4fbb-9be3-7236ff8899b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QA test'])[1]/preceding::div[2]</value>
      <webElementGuid>9e6fe119-d53f-4b11-877f-5cecc40779fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Первчиный приём']/parent::*</value>
      <webElementGuid>a453586d-7b00-4451-87aa-8b94db870d8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/div/div[2]/div/div[2]</value>
      <webElementGuid>7e9bdba6-a970-4d9a-b892-f978b67def7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-10-option-1' and (text() = 'Первичный приём' or . = 'Первчиный приём')]</value>
      <webElementGuid>0293cb18-ba50-49aa-aa38-ce3337d8dd37</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
