<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__nachalo_priema</name>
   <tag></tag>
   <elementGuidId>5fb544ef-e9c7-42c4-a88f-7ab09d5e50b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#qeXgr3ZRT9zRnEgGXomNg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/label/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>724af799-a609-47b2-9130-53d51dc17a5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>qeXgr3ZRT9zRnEgGXomNg</value>
      <webElementGuid>12ce7e76-1d40-49af-8a72-3df5c01c023c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_input__Xf-yT</value>
      <webElementGuid>b1193353-aa6f-4dab-b2dc-31ee94dcd7c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>time</value>
      <webElementGuid>a540317a-0125-440f-bede-8e2350f46ab4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a75e1e83-f436-469b-9c78-c72d0208e918</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>08:10</value>
      <webElementGuid>f31a2676-e7fe-42e2-adec-718bca4dd558</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;qeXgr3ZRT9zRnEgGXomNg&quot;)</value>
      <webElementGuid>3a8d2685-1831-4289-8cca-fc84514cf796</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='qeXgr3ZRT9zRnEgGXomNg']</value>
      <webElementGuid>bae16562-973e-4e38-9407-49980c651e39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='drawer']/div/div/div/form/div/div[4]/div/div[3]/label/input</value>
      <webElementGuid>00821bd2-5c65-427a-9b89-42cfe56246c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/label/input</value>
      <webElementGuid>051102f1-b10e-419d-b728-e5cc534cbe60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'qeXgr3ZRT9zRnEgGXomNg' and @type = 'time']</value>
      <webElementGuid>a843e88e-a9ac-40ce-9dc2-643399af134d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
