<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__okonchanie_priema</name>
   <tag></tag>
   <elementGuidId>975b4e56-7e03-441c-8857-f72d49425c4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#qeXgr3ZRT9zRnEgGXomNg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/label/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9f2eecf7-10fc-4e73-b01f-c8412feeb878</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>qeXgr3ZRT9zRnEgGXomNg</value>
      <webElementGuid>9556a478-5030-4d8a-84e1-4f2895fec54c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_input__Xf-yT</value>
      <webElementGuid>0700bbb7-b0bf-44bc-9a1f-8ca26774dc87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>time</value>
      <webElementGuid>e01b0b8d-4045-407c-80d2-d11eb648f759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3b4c87b2-27c5-4a6d-813d-d3c5f3545a32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>08:10</value>
      <webElementGuid>f67cdca9-fd27-47b7-ad5e-05c1707e2a5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;qeXgr3ZRT9zRnEgGXomNg&quot;)</value>
      <webElementGuid>897d56d0-c94d-4706-b2eb-4c30b2aea716</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='qeXgr3ZRT9zRnEgGXomNg']</value>
      <webElementGuid>27501b21-dd67-4eb6-85f2-a5fe0a82645d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='drawer']/div/div/div/form/div/div[4]/div/div[3]/label/input</value>
      <webElementGuid>3fd3bacd-09b5-4725-82b8-94c6ab26746c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/label/input</value>
      <webElementGuid>deb12643-f226-46c2-98bb-0591037f810d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'qeXgr3ZRT9zRnEgGXomNg' and @type = 'time']</value>
      <webElementGuid>38af5afd-c9b1-4170-9a9b-42825b856eea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
