<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_cel_vizita</name>
   <tag></tag>
   <elementGuidId>a9e73edb-bb61-45a2-90a1-fce714d82a32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='drawer']/div/div/div/form/div/div[5]/div/textarea</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ShWbRhnAdo4yMsHbG3g3a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>9af26851-1196-41cf-87f7-8eed1d3c8f0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>a4bad2fd-d398-4122-9dc1-6b02b4e505ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ShWbRhnAdo4yMsHbG3g3a</value>
      <webElementGuid>c6c4d0e5-6774-4fa3-93f0-3d2bcb194049</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>13e96baa-b791-471b-af3f-6bca77fca630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input styles_textarea__3FuFL</value>
      <webElementGuid>69c92e12-d967-4f46-bc9c-57f0f542262f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Автотест. Цель визита</value>
      <webElementGuid>bc9fe0d4-6fd6-4747-8394-8f5cb47b5627</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ShWbRhnAdo4yMsHbG3g3a&quot;)</value>
      <webElementGuid>852d8d02-8ce4-4f3c-9ddc-9e90d8a8e1b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='ShWbRhnAdo4yMsHbG3g3a']</value>
      <webElementGuid>383b6be5-33c4-4c0d-8060-d30473ce3c1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='drawer']/div/div/div/form/div/div[4]/div/textarea</value>
      <webElementGuid>fff7cbe3-bed5-4102-8f2f-38864b72a0ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Другое'])[1]/following::textarea[1]</value>
      <webElementGuid>ed3a8ab9-5c38-49be-b974-0e56215ff01c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='По'])[1]/following::textarea[1]</value>
      <webElementGuid>7235c410-e172-45e5-abc2-f1d57fa53184</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Цель визита'])[1]/preceding::textarea[1]</value>
      <webElementGuid>b36093ed-057e-4ea0-9ff3-a2b7fb0a9381</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Услуги'])[1]/preceding::textarea[1]</value>
      <webElementGuid>b34964fa-4a95-447b-8447-dbb4c5266e94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Автотест. Цель визита']/parent::*</value>
      <webElementGuid>4998f342-c4ef-4a4f-8752-9a818163d9d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>7db71952-98a9-4844-a212-ebce7382d00c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'ShWbRhnAdo4yMsHbG3g3a' and (text() = 'Автотест. Цель визита' or . = 'Автотест. Цель визита')]</value>
      <webElementGuid>6376a5fd-2b65-4f9b-aca5-0ff211f2e5f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
