<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Patient_Avtotest QA Regressovich</name>
   <tag></tag>
   <elementGuidId>9dc886a9-8ef9-419c-b3eb-a0084f74a43b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-7-option-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#react-select-7-option-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c1135649-87db-40ca-8669-1776fc65b646</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> css-1yxc0mn-option</value>
      <webElementGuid>6701259b-6f39-4dad-aa72-da3c5d2dae87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-7-option-1</value>
      <webElementGuid>990457f3-18ac-4625-a0d5-2f5b8ee9db1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>a6e65258-d752-4b91-8631-0d3151008b1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Avtotest QA Regressovich, 11.05.1995, +7 (965) 644-65-63</value>
      <webElementGuid>98d26078-9ffa-49d8-9c3d-db91536e341f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-7-option-1&quot;)</value>
      <webElementGuid>726ee390-5608-48e4-b4fe-8e03308b8ae9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-7-option-1']</value>
      <webElementGuid>aaef79e0-3fce-4cc6-b1d3-10ffa4dd8023</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='drawer']/div/div/div/form/div/div/div/div/div/div/div/div[2]/div/div[2]</value>
      <webElementGuid>51a6e308-194e-4deb-9493-0daf8e6f46cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Добавить пациента'])[1]/following::div[1]</value>
      <webElementGuid>618629b4-1d8b-4d86-a3c7-28cb9668f11f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='avto'])[1]/following::div[7]</value>
      <webElementGuid>4ddd1f02-7542-43e3-a92a-71175b59eb72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Имя'])[1]/preceding::div[1]</value>
      <webElementGuid>d8ad61b5-5251-4b2e-bcfa-8a7409030d9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Отчество'])[1]/preceding::div[2]</value>
      <webElementGuid>ec4bd027-2964-45c6-813c-ccfdc4c5a299</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Avtotest QA Regressovich, 11.05.1995, +7 (965) 644-65-63']/parent::*</value>
      <webElementGuid>be78c50f-b5cd-4b4a-ae89-52a913c69401</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/div[2]/div/div[2]</value>
      <webElementGuid>4057afbd-b3ed-4fe1-b8d2-5c2aae623ece</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-7-option-1' and (text() = 'Avtotest QA Regressovich, 11.05.1995, +7 (965) 644-65-63' or . = 'Avtotest QA Regressovich, 11.05.1995, +7 (965) 644-65-63')]</value>
      <webElementGuid>7be4e818-957b-43b1-ae8e-5f0aaf5ee3b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
