<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>status_podtvershden</name>
   <tag></tag>
   <elementGuidId>58e42215-9da6-4bf7-a79c-c050c1074782</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Подтвержден' or . = 'Подтвержден')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id = 'react-select-12-option-0' and (text() = 'Подтвержден' or . = 'Подтвержден')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#react-select-12-option-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c7846bfd-0889-4bfa-81bb-a332e7c50818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> css-1qs9gy9-option</value>
      <webElementGuid>cf70ccff-24eb-43fe-9b83-1a0a59689198</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-12-option-0</value>
      <webElementGuid>e9219aa4-4fe3-4442-a2d1-9b41e6e94a42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>6f0ffc3e-4ba3-4366-90e4-f52ad9a82518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Подтвержден</value>
      <webElementGuid>b5979aa7-7043-44d0-a1d4-af77784edc30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-12-option-0&quot;)</value>
      <webElementGuid>d0ae7517-ce76-4400-89e7-7b4e9227c53a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-12-option-0']</value>
      <webElementGuid>fc84902e-90af-4e61-b5f4-dec229bf8c62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='drawer']/div/div/div/form/div[2]/div/div/div/div/div[2]/div/div</value>
      <webElementGuid>d4b26011-2638-412b-8934-ed350cfccf98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Не подтвержден'])[1]/following::div[4]</value>
      <webElementGuid>f76397e8-b636-4881-91a4-7c75f17f0bfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='option Не подтвержден, selected.'])[1]/following::div[7]</value>
      <webElementGuid>a78eed20-8e65-432b-a00c-fd6bfa8c003f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Назначить'])[1]/preceding::div[1]</value>
      <webElementGuid>6867e0b8-6e54-4fb2-ac34-2ffae8e7fd87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Подтвержден']/parent::*</value>
      <webElementGuid>a26edd9c-d93d-4c22-b0be-f3fa4618ffb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/div/div/div/div[2]/div/div</value>
      <webElementGuid>fe114fc9-af04-498a-9b1a-dcfeafef6273</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-12-option-0' and (text() = 'Подтвержден' or . = 'Подтвержден')]</value>
      <webElementGuid>0ad279ed-a743-4c56-8bfb-c4ef44322b8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
