<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tab_naznachit</name>
   <tag></tag>
   <elementGuidId>fadb400c-cfd7-487c-aefa-0be5e2439080</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[(text() = 'Назначить' or . = 'Назначить')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.ant-btn.ant-btn-primary.ant-btn-lg.styles_button__3pqej.styles_large__1J0A5.styles_primary__2Afkd.styles_button__1OfyD > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>cb56108a-acd4-4258-923e-fd02e88e4ef9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Назначить</value>
      <webElementGuid>28825d08-17a8-446c-8023-cc985bb002ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;drawer&quot;)/div[@class=&quot;styles_wrapper__3fhNR&quot;]/div[@class=&quot;styles_wrapper__background__i5gz- styles_wrapper__background_active__1WfBI&quot;]/div[@class=&quot;styles_wrapper__content__3_KkI styles_wrapper__content_active__3cggn&quot;]/form[@class=&quot;styles_container__2kCJE&quot;]/div[@class=&quot;actions__container&quot;]/div[@class=&quot;styles_actions__3Oxx_&quot;]/button[@class=&quot;ant-btn ant-btn-primary ant-btn-lg styles_button__3pqej styles_large__1J0A5 styles_primary__2Afkd styles_button__1OfyD&quot;]/span[1]</value>
      <webElementGuid>5a3ada71-b945-4632-af36-17a5d966f6bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='drawer']/div/div/div/form/div[2]/div/button/span</value>
      <webElementGuid>de8eaa4c-a249-4a85-b23a-328675b96af8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Подтвержден'])[1]/following::span[2]</value>
      <webElementGuid>823fdfde-e96c-40a8-9e8b-7e931d9a6115</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Добавить услугу'])[1]/following::span[4]</value>
      <webElementGuid>7ed2007d-2d47-41d2-8245-f77c76b9949a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Назначить']/parent::*</value>
      <webElementGuid>f7fac872-7742-4bf0-87b5-407550d97443</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span</value>
      <webElementGuid>ef91e5fd-9551-4111-9a26-278e0f6f7078</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Назначить' or . = 'Назначить')]</value>
      <webElementGuid>31e7ad4b-1ec9-4bca-9c50-38e5b62f556f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
