<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tab_pereiti_v_profile_in_zapis_na_priem</name>
   <tag></tag>
   <elementGuidId>362246ae-b748-4c1d-beef-16a3689333d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.styles_go_to_profile__1NX6m</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='drawer']/div/div/div/form/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b9ce9b61-bc87-4c52-930b-66adc987319a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_go_to_profile__1NX6m</value>
      <webElementGuid>8abc6ca3-4d2a-431d-8b4a-ef02054aad4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/patients/21480/profile?returnURL=/schedule?date=2022-10-04&amp;time=08:00&amp;doctor_id=68&amp;branch_office=135&amp;patientId=21480</value>
      <webElementGuid>ce69dc24-cc61-4bdb-b66e-0dd8eeea7026</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Перейти в профиль пациента</value>
      <webElementGuid>c823776c-e3c3-42d5-b48f-cbc872cc7fe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;drawer&quot;)/div[@class=&quot;styles_wrapper__3fhNR&quot;]/div[@class=&quot;styles_wrapper__background__i5gz- styles_wrapper__background_active__1WfBI&quot;]/div[@class=&quot;styles_wrapper__content__3_KkI styles_wrapper__content_active__3cggn&quot;]/form[@class=&quot;styles_container__2kCJE&quot;]/div[@class=&quot;styles_content__container__20ZQn&quot;]/div[@class=&quot;styles_container__2tSlF&quot;]/a[@class=&quot;styles_go_to_profile__1NX6m&quot;]</value>
      <webElementGuid>83e8b5a1-d94c-494c-a419-d41ead71948a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='drawer']/div/div/div/form/div/div/a</value>
      <webElementGuid>04333772-c116-4c3a-b428-cf8ce7932319</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Перейти в профиль пациента')]</value>
      <webElementGuid>b1ad80c7-2863-40de-872d-72bef9e6b139</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Данные пациента'])[1]/following::a[1]</value>
      <webElementGuid>c2b50fa7-dfc6-4a73-a5cf-9d795f5be24b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Специалист'])[1]/following::a[1]</value>
      <webElementGuid>bd09de89-bce4-4b43-adf6-454f57eafed5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Андропов'])[1]/preceding::a[1]</value>
      <webElementGuid>a7b9f208-1da6-4941-8a9e-e07946d64c3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Имя'])[1]/preceding::a[1]</value>
      <webElementGuid>6dcfaea7-1694-4b39-8faf-7fae2208d481</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Перейти в профиль пациента']/parent::*</value>
      <webElementGuid>973e6936-1ad2-44da-8bdf-3624ec5d9b24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/patients/21480/profile?returnURL=/schedule?date=2022-10-04&amp;time=08:00&amp;doctor_id=68&amp;branch_office=135&amp;patientId=21480')]</value>
      <webElementGuid>852593c1-346f-492e-81ef-d175a92aa826</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/a</value>
      <webElementGuid>30c95e30-8a56-4abe-93e8-9eb1c1e115f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/patients/21480/profile?returnURL=/schedule?date=2022-10-04&amp;time=08:00&amp;doctor_id=68&amp;branch_office=135&amp;patientId=21480' and (text() = 'Перейти в профиль пациента' or . = 'Перейти в профиль пациента')]</value>
      <webElementGuid>6680dee2-076b-4cf3-8fbe-13a2e0a32894</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
