<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verif_status_add</name>
   <tag></tag>
   <elementGuidId>273539cd-cfa1-4088-99bb-c5425528975e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[text() = 'Подтвержден']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.styles_selectInputWrapper__p580E.styles_selector__2mUxR</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>69ebfa7b-5c1c-4a30-9f50-f5e9722139d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_selectInputWrapper__p580E styles_selector__2mUxR</value>
      <webElementGuid>c98e6cf0-ad92-4548-8002-752645e95971</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Подтвержден</value>
      <webElementGuid>805f6507-96cd-428c-ab80-0e966222ee40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;drawer&quot;)/div[@class=&quot;styles_wrapper__3fhNR&quot;]/div[@class=&quot;styles_wrapper__background__i5gz- styles_wrapper__background_active__1WfBI&quot;]/div[@class=&quot;styles_wrapper__content__3_KkI styles_wrapper__content_active__3cggn&quot;]/form[@class=&quot;styles_container__2kCJE&quot;]/div[@class=&quot;actions__container&quot;]/div[@class=&quot;styles_actions__3Oxx_&quot;]/div[@class=&quot;styles_selectInputContainer__1vEHJ&quot;]/div[@class=&quot;styles_selectInputWrapper__p580E styles_selector__2mUxR&quot;]</value>
      <webElementGuid>3a3b8f30-8923-48eb-ac61-3eeba6d6d7b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='drawer']/div/div/div/form/div[2]/div/div/div</value>
      <webElementGuid>57225e1a-a12e-4903-9224-6381e68369ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Добавить услугу'])[1]/following::div[12]</value>
      <webElementGuid>5c2049b3-918f-4b33-9d86-dfd05e755b99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Услуги'])[1]/following::div[20]</value>
      <webElementGuid>1c42c502-582b-4f57-8d1a-1d64eb2e5aa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Назначить'])[1]/preceding::div[6]</value>
      <webElementGuid>e1d82c49-8d87-42d8-9da6-944b1e0ad3f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/div/div</value>
      <webElementGuid>47d3712f-ca7f-4f22-ac22-71869d748d80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Подтвержден' or . = 'Подтвержден')]</value>
      <webElementGuid>9197b2ee-99e7-46b8-a343-e1372d8c5cfc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
