<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_back_in_profile_in_profile</name>
   <tag></tag>
   <elementGuidId>3bdceac4-f0ef-40fd-a13c-2f87c5a95747</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.styles_button__1_cpq</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type = 'button' and (text() = '←  Назад' or . = '←  Назад')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>21f54125-9486-46ef-bd25-ac3ce8f213e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d6b85cc0-b614-4cb7-8102-104ea446ddb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_button__1_cpq</value>
      <webElementGuid>0e5aecbe-f7dd-42fa-86d3-64c85309a205</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>←  Назад</value>
      <webElementGuid>6c224a16-c665-4950-a88a-db1174ea0f01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;styles_layout__wrapper__2zeB1&quot;]/div[@class=&quot;styles_layout__container__3D3Vr styles_layout__container_admin__2X_qx&quot;]/main[@class=&quot;styles_layout__content__1BAJN styles_layout__content_admin__WVT00&quot;]/section[@class=&quot;styles_contentLayout__1rqiW&quot;]/div[@class=&quot;styles_wrapper__10O36&quot;]/button[@class=&quot;styles_button__1_cpq&quot;]</value>
      <webElementGuid>b9a7c67f-6eee-4661-8246-96b5043c73c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>4c83de0a-a240-47ae-a1b4-e61d27aa6c6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/main/section/div/button</value>
      <webElementGuid>27648854-3f75-413d-aafd-32ca53e80ba5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Шаблоны осмотра'])[1]/following::button[1]</value>
      <webElementGuid>99ea4466-039b-4136-b311-c637ffbcda24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Юридические лица'])[1]/following::button[1]</value>
      <webElementGuid>78ffe884-317d-44b7-acd5-2c798e62c318</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QA Regressovich Avtotest, 27 лет (11.05.1995 г.р.)'])[1]/preceding::button[1]</value>
      <webElementGuid>252189b4-db50-4a58-beb0-6d1d5714472d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Профиль'])[1]/preceding::button[1]</value>
      <webElementGuid>f3ad46c7-0e2e-4818-bb61-4f20f564b703</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/button</value>
      <webElementGuid>ab04c7db-bd31-4597-b9c3-456c9abfdffe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '←  Назад' or . = '←  Назад')]</value>
      <webElementGuid>c743ca24-0739-4645-9657-a4fb80713f01</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
