<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>number_ambulat_card_in_profile</name>
   <tag></tag>
   <elementGuidId>fdca4f7e-17b8-445a-b3d8-aa0006ffc575</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.styles_outpatientCard__value__3JAN6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[(text() = '8437572726432NK' or . = '8437572726432NK')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>3f37a1f8-7f24-4f55-adb4-f3ba8672bc50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_outpatientCard__value__3JAN6</value>
      <webElementGuid>1b43da26-c968-440e-a670-c0279ef02554</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>8437572726432NK</value>
      <webElementGuid>99d24c03-9f0a-4369-9dde-55176b49bf86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;styles_layout__wrapper__2zeB1&quot;]/div[@class=&quot;styles_layout__container__3D3Vr styles_layout__container_admin__2X_qx&quot;]/main[@class=&quot;styles_layout__content__1BAJN styles_layout__content_admin__WVT00&quot;]/section[@class=&quot;styles_contentLayout__1rqiW&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;profile&quot;]/div[@class=&quot;styles_profile__head__1Arb7&quot;]/div[@class=&quot;outpatientCard&quot;]/p[@class=&quot;styles_outpatientCard__value__3JAN6&quot;]</value>
      <webElementGuid>be43b83b-07c3-47ca-847c-1541f13d889f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/main/section/div[2]/div[2]/div/div/p[2]</value>
      <webElementGuid>e848934b-d367-4883-8cf1-a3835a03d225</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Анкета'])[1]/following::p[2]</value>
      <webElementGuid>3e6d081e-d30a-45c6-8520-416caf95ed78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Профиль'])[1]/following::p[2]</value>
      <webElementGuid>25fb07c1-dc07-4bd6-8865-db9cc4664fe4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Редактировать данные'])[1]/preceding::p[1]</value>
      <webElementGuid>796649d4-0784-4721-83bf-c40728a09d36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Удалить пациента'])[1]/preceding::p[1]</value>
      <webElementGuid>3bcc6928-bdd7-4b4a-9836-345e25e9dd67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='8437572726432NK']/parent::*</value>
      <webElementGuid>ad82222d-da10-492e-b4bb-6a18e2eb62ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/p[2]</value>
      <webElementGuid>1a4cc885-a855-43e2-92dc-17af9de95095</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '8437572726432NK' or . = '8437572726432NK')]</value>
      <webElementGuid>326d907b-1430-4e64-b657-df317a4804f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
