<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verif_Patient Create  In card</name>
   <tag></tag>
   <elementGuidId>b9d2c36c-fd85-4229-9ecd-300b4df1cafb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '${GlobalVariable.Test_patient2_FIO_full}' or . = '${GlobalVariable.Test_patient2_FIO_full}')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[(text() = 'Patient Create Тестович In card' or . = 'Patient Create Тестович In card')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.styles_patient__name__11BU0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d1408238-2df6-4bc9-8557-022003a2b3a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_patient__name__11BU0</value>
      <webElementGuid>0bfd36ca-d468-44fb-a26b-77548e7af926</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>${GlobalVariable.Test_patient2_FIO_full}</value>
      <webElementGuid>29a657c8-53a3-4993-b463-047fd8821083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;drawer&quot;)/div[@class=&quot;styles_wrapper__3fhNR&quot;]/div[@class=&quot;styles_wrapper__background__i5gz- styles_wrapper__background_active__1WfBI&quot;]/div[@class=&quot;styles_wrapper__content__3_KkI styles_wrapper__content_active__3cggn&quot;]/div[@class=&quot;styles_container__3ivyS&quot;]/div[@class=&quot;styles_container__1zr_3&quot;]/div[@class=&quot;styles_container__2UbMH&quot;]/div[@class=&quot;styles_container__18AaY&quot;]/div[@class=&quot;styles_content__container__1FikG&quot;]/div[@class=&quot;styles_content__1YTzU&quot;]/div[@class=&quot;styles_info__1xIDw&quot;]/span[@class=&quot;styles_patient__name__11BU0&quot;]</value>
      <webElementGuid>05c616cf-8692-409f-9889-8b4ad2739872</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='drawer']/div/div/div/div[2]/div/div[2]/div/div/div[3]/div[2]/span</value>
      <webElementGuid>958f51ed-3f2b-4f87-bc54-e32a3ba14751</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Пациент'])[1]/following::span[1]</value>
      <webElementGuid>cf126b43-817a-4744-8b21-f542ec71fce9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Врач'])[1]/following::span[1]</value>
      <webElementGuid>de0b55d0-2a40-4493-a1d7-29118b2c82f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Цель визита'])[1]/preceding::span[2]</value>
      <webElementGuid>fd9165e4-883b-469d-ad64-5de939a51656</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Начать прием'])[1]/preceding::span[2]</value>
      <webElementGuid>a718d775-b458-435f-bf35-bed307ec2ef3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Patient Create Тестович In card']/parent::*</value>
      <webElementGuid>a4266e65-d51e-4a67-a365-0fb8d2f5e985</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/span</value>
      <webElementGuid>2f56dbe0-9fe1-4c90-b8ce-1fb2b5960669</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Patient Create Тестович In card' or . = 'Patient Create Тестович In card')]</value>
      <webElementGuid>1db6a6d7-5f4a-402b-bef8-be4d802c7312</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
