<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verif_Patient Create  In card</name>
   <tag></tag>
   <elementGuidId>b9d2c36c-fd85-4229-9ecd-300b4df1cafb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[(text() = 'Patient Create Тестович In card' or . = 'Patient Create Тестович In card')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.styles_patient__name__11BU0</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '${GlobalVariable.Test_patient2_FIO_full}' or . = '${GlobalVariable.Test_patient2_FIO_full}')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>239584f6-2063-4bfd-813b-315db603506a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_patient__name__11BU0</value>
      <webElementGuid>540e2373-b1fa-4fc8-a871-31b712f0678f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>${GlobalVariable.Test_patient2_FIO_full}</value>
      <webElementGuid>a05df8b0-72f9-429b-bf0a-7a5081e4d4b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;drawer&quot;)/div[@class=&quot;styles_wrapper__3fhNR&quot;]/div[@class=&quot;styles_wrapper__background__i5gz- styles_wrapper__background_active__1WfBI&quot;]/div[@class=&quot;styles_wrapper__content__3_KkI styles_wrapper__content_active__3cggn&quot;]/div[@class=&quot;styles_container__3ivyS&quot;]/div[@class=&quot;styles_container__1zr_3&quot;]/div[@class=&quot;styles_container__2UbMH&quot;]/div[@class=&quot;styles_container__18AaY&quot;]/div[@class=&quot;styles_content__container__1FikG&quot;]/div[@class=&quot;styles_content__1YTzU&quot;]/div[@class=&quot;styles_info__1xIDw&quot;]/span[@class=&quot;styles_patient__name__11BU0&quot;]</value>
      <webElementGuid>e64d6181-78da-4721-8dc2-4604bbe817d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='drawer']/div/div/div/div[2]/div/div[2]/div/div/div[3]/div[2]/span</value>
      <webElementGuid>8598d782-fe49-415e-8ff7-9ebd5b6d0122</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Пациент'])[1]/following::span[1]</value>
      <webElementGuid>a664fb5a-72fb-4485-8484-0200534542b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Врач'])[1]/following::span[1]</value>
      <webElementGuid>f8e0f322-7fb6-459c-b6e4-f4f3b8cd94a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Цель визита'])[1]/preceding::span[2]</value>
      <webElementGuid>83cfaf7b-f70c-4149-a57f-0eb8bc303838</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Начать прием'])[1]/preceding::span[2]</value>
      <webElementGuid>4bbc2f2a-4af9-4157-a1ad-2304ced299eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Patient Create Тестович In card']/parent::*</value>
      <webElementGuid>3ac84584-dced-4eca-b334-190f325098c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/span</value>
      <webElementGuid>f58f3143-0332-4f0b-b95b-6310cb1c8a6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Patient Create Тестович In card' or . = 'Patient Create Тестович In card')]</value>
      <webElementGuid>61f61c8e-5c32-484e-9201-7e98e3471b53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
