<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verif_email_in_profile</name>
   <tag></tag>
   <elementGuidId>22f5689d-8526-477a-92d7-99c2c823c86a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#_VETJzo3TOpIxdZkfxZOp</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @value = '${GlobalVariable.Test_email}']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div[2]/main/section/div[2]/div[2]/form/div[2]/div/label/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>090c5acd-dc19-4b31-8e3d-ac1689b250d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_VETJzo3TOpIxdZkfxZOp</value>
      <webElementGuid>b144189d-f2b6-44d3-81f1-ab4382f4a1ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_input__Xf-yT styles_field__2KsgS styles_field__231__3U3JZ</value>
      <webElementGuid>62686a19-ddd7-47de-a992-78320a020b3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4bc2a15d-cbf3-48c3-99ec-4e718b715f0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4a9ca98e-002f-4f85-93bd-447aa963172d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>${GlobalVariable.Test_email}</value>
      <webElementGuid>95e0717a-bc58-4f4a-bfd7-8ab2902e655f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_VETJzo3TOpIxdZkfxZOp&quot;)</value>
      <webElementGuid>0f480e20-3a08-4de8-b8bc-ea0ca2084dd6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='_VETJzo3TOpIxdZkfxZOp']</value>
      <webElementGuid>ddeb1b00-20e7-44b5-a1ba-1699a81c1901</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/main/section/div[2]/div[2]/form/div[2]/div/label/input</value>
      <webElementGuid>569af13c-0132-4e8f-b1c5-2624be6f7b05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/label/input</value>
      <webElementGuid>c3677921-0a7c-4711-886f-0bdcfb9cb2e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '_VETJzo3TOpIxdZkfxZOp' and @type = 'text']</value>
      <webElementGuid>e68940b7-a49b-4f59-894a-cd11fff5131f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
