<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>alert_success_redactor_patient</name>
   <tag></tag>
   <elementGuidId>b583f79b-bf39-4202-8a9b-98fc65d0c545</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[(text() = 'Успешно' or . = 'Успешно')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>9098d2ed-049e-474a-a3f4-6f9f7a7a9245</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d70da2a5-56f5-4c3b-ae35-51843124c3b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Успешно</value>
      <webElementGuid>675599f0-a6fc-4aed-b25a-5c477539f1b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[5]/div[@class=&quot;ant-message&quot;]/div[1]/div[@class=&quot;ant-message-notice&quot;]/div[@class=&quot;ant-message-notice-content&quot;]/div[@class=&quot;ant-message-custom-content ant-message-success&quot;]/span[1]/div[@class=&quot;styles_container__3Xmpa&quot;]/p[@class=&quot;text&quot;]</value>
      <webElementGuid>e98407a7-913d-49a1-95aa-47fa7d2f0359</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Отмена'])[1]/following::p[1]</value>
      <webElementGuid>0bcdf6ab-7905-4ccc-8908-2988b8998778</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Добавить'])[1]/following::p[1]</value>
      <webElementGuid>a6c75f47-a4bc-4b5b-b11e-f2a7139fda2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Успешно']/parent::*</value>
      <webElementGuid>5fa02dce-caf7-434a-8669-bdf4dd8e14f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/p</value>
      <webElementGuid>b645aee1-bc12-44b2-baac-ef411943f058</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Успешно' or . = 'Успешно')]</value>
      <webElementGuid>48794c48-8595-4037-b0a8-3c61af63d07d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
