<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__adress_in_redactor_profil_patient</name>
   <tag></tag>
   <elementGuidId>e8a1757d-ec60-48b4-9b43-a86b29b292b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#eWinkOT5DS7Axhxu4scuk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div[2]/main/section/form/div[3]/div[2]/div/div[3]/label/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c0fdf80a-3923-49f8-9208-a1b940594035</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>eWinkOT5DS7Axhxu4scuk</value>
      <webElementGuid>3784fabe-34d4-4d41-ab0e-95b7d58b2394</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_input__Xf-yT styles_field-address__1kVlG</value>
      <webElementGuid>3eaa719b-3f93-44f4-9067-c5cc231c2a63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>472cc8b7-810f-4ad7-967d-c7e13ec742f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>С</value>
      <webElementGuid>ad0f53e0-387a-4cb0-8698-8572dc2fc8a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;eWinkOT5DS7Axhxu4scuk&quot;)</value>
      <webElementGuid>4b3fb889-774e-476b-8747-31b574d2afef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='eWinkOT5DS7Axhxu4scuk']</value>
      <webElementGuid>93c8da00-cc47-4713-bd86-b5ad86d41819</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/main/section/form/div[3]/div[2]/div/label[3]/input</value>
      <webElementGuid>e5cf79b9-5588-4881-bb5d-7e33d54869ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[3]/input</value>
      <webElementGuid>6818db4c-247b-4345-8652-aadd9bcf3606</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'eWinkOT5DS7Axhxu4scuk']</value>
      <webElementGuid>f704f780-d681-4fc5-a515-f76b9783c700</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
