<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Na-mwZy13pwumKME5P7b8</name>
   <tag></tag>
   <elementGuidId>43e260af-900b-4622-8de8-7a1f427429e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Na-mwZy13pwumKME5P7b8']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Na-mwZy13pwumKME5P7b8</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>da422c26-c6f7-4ffb-8427-df8ac49378f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Na-mwZy13pwumKME5P7b8</value>
      <webElementGuid>bf15a835-9dd2-4794-be4c-87f75d4a904f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_input__Xf-yT styles_field-address__1kVlG</value>
      <webElementGuid>5b0a8d28-c4b4-4802-8de8-58b8059b4cdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>bcd1753c-b81d-4a4f-84e4-c13ee6aba6f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Na-mwZy13pwumKME5P7b8&quot;)</value>
      <webElementGuid>e216a159-1761-432c-9368-3bbdff2c00ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Na-mwZy13pwumKME5P7b8']</value>
      <webElementGuid>45573f08-99f2-4ecc-9755-4d456c6381f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/main/section/form/div[3]/div[2]/div/label[3]/input</value>
      <webElementGuid>bb5836f1-28c9-4f80-90ac-9ca8fb17a1b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[3]/input</value>
      <webElementGuid>544ce311-6389-4344-aa3f-ec9be0635cf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Na-mwZy13pwumKME5P7b8']</value>
      <webElementGuid>91482c15-b0ae-4670-a406-ff1da24b5087</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
