<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__adress_in_redactor_profil_patient</name>
   <tag></tag>
   <elementGuidId>e8a1757d-ec60-48b4-9b43-a86b29b292b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@class,'styles_field-address')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#eWinkOT5DS7Axhxu4scuk</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bcc05a98-8112-47ee-874e-bd93e517cc84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>eWinkOT5DS7Axhxu4scuk</value>
      <webElementGuid>fc369561-36c1-4b26-9244-14e617a7dd7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_input__Xf-yT styles_field-address__1kVlG</value>
      <webElementGuid>09d7cb25-12a7-43e7-a66a-3d09d79db6b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ebcd7be6-0e89-40e1-88b5-fb0ad21ddde4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>С</value>
      <webElementGuid>694479d4-d6fa-4579-a6b1-49383b6edd85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;eWinkOT5DS7Axhxu4scuk&quot;)</value>
      <webElementGuid>acbb5129-d093-4ccb-82ce-58205dbe9538</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='eWinkOT5DS7Axhxu4scuk']</value>
      <webElementGuid>cd9809de-1449-4ab9-a80b-f0ec3910fb34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/main/section/form/div[3]/div[2]/div/label[3]/input</value>
      <webElementGuid>c29d8c91-f99c-4a98-8027-bb541b0feeb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[3]/input</value>
      <webElementGuid>1b0150ac-e635-41ee-a740-b746ddd68431</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'eWinkOT5DS7Axhxu4scuk']</value>
      <webElementGuid>ed4fee90-d7ca-4d04-a237-2b8146d1a745</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
