<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tab_documents_ib_priem</name>
   <tag></tag>
   <elementGuidId>62eeb34a-0022-4491-8ca4-043d2c9849af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rc-tabs-0-tab-documents</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@role = 'tab' and (text() = 'Документы')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7b7f7bf4-8450-4482-a8e7-84dd6c8141c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>9a6234bc-2a84-428f-85b2-92a0138699e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>926f3e8a-7917-4c59-b61b-47abcbbe8181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-tabs-tab-btn</value>
      <webElementGuid>61a6659d-8553-4ef8-bc42-89c61ce352d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6d8dedf1-1444-498f-b1cc-86daa5230194</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rc-tabs-0-tab-documents</value>
      <webElementGuid>ea1da08f-e30a-40fd-8bfa-5d3562f1a00f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>rc-tabs-0-panel-documents</value>
      <webElementGuid>2a497007-4a04-46de-8b80-1bbe961d8b57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Документы</value>
      <webElementGuid>90b11be8-b7eb-4b27-a5b3-ad9c968ac83d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-tabs-0-tab-documents&quot;)</value>
      <webElementGuid>81d1eb8c-7729-49e1-aa29-3ed683c6ba51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>35c8ff9c-0005-48f1-ad29-c51285c58d11</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
