<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tab_adress</name>
   <tag></tag>
   <elementGuidId>9b1a2c6d-6e10-41cd-98a5-2084455e9af6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/main/section/form/div[3]/div[2]/div/label[3]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label.styles_inputWrapper__3YFF2.wrapper-field-address > span.styles_label__1CZ6I</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>128bb6e4-6b00-4f68-bc55-6ac6674bf640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_label__1CZ6I</value>
      <webElementGuid>256f20f2-71d5-4f4b-b6e0-711b9b6185d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Адрес</value>
      <webElementGuid>b73a7219-da49-4a82-ac17-1b0391c39297</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;styles_layout__wrapper__2zeB1&quot;]/div[@class=&quot;styles_layout__container__3D3Vr styles_layout__container_admin__2X_qx&quot;]/main[@class=&quot;styles_layout__content__1BAJN styles_layout__content_admin__WVT00&quot;]/section[@class=&quot;styles_contentLayout__1rqiW&quot;]/form[@class=&quot;container&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;fields&quot;]/div[@class=&quot;styles_container-fields__17jaw&quot;]/label[@class=&quot;styles_inputWrapper__3YFF2 wrapper-field-address&quot;]/span[@class=&quot;styles_label__1CZ6I&quot;]</value>
      <webElementGuid>3770cc7a-33c3-43fe-bf74-81b29bd79c46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/main/section/form/div[3]/div[2]/div/label[3]/span</value>
      <webElementGuid>35d5090a-eee6-483c-b3a2-45ddddd33691</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Город'])[1]/following::span[1]</value>
      <webElementGuid>96716d28-6f8e-4e1b-8bb2-67e8cc5fd2e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Страна'])[1]/following::span[2]</value>
      <webElementGuid>de6dcae4-6470-49d7-bfb2-bfc186092e80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ДОПОЛНИТЕЛЬНАЯ ИНФОРМАЦИЯ'])[1]/preceding::span[1]</value>
      <webElementGuid>55fdf312-271e-4a93-8004-fcfd1e9a3194</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Номер амбулаторной карты'])[1]/preceding::span[1]</value>
      <webElementGuid>be741c2d-c77c-4ccb-80ae-e645d2547e1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Адрес']/parent::*</value>
      <webElementGuid>2965f730-80c9-4182-82c0-14e4a2fb6198</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[3]/span</value>
      <webElementGuid>96521925-a965-4772-9224-ac417ac3f4a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Адрес' or . = 'Адрес')]</value>
      <webElementGuid>b08778fb-5dd4-493d-b546-8e7c74786aa5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
