<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>2_usluga_vkladka_v2</name>
   <tag></tag>
   <elementGuidId>08bad3a8-ecc0-4d72-8593-231330180db0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='drawer']/div[2]/div/div/div[2]/div/div/div/div/div/div[2]/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#react-select-7-option-1</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[(text() = 'Тестовая услуга два' or . = 'Тестовая услуга два')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>12b67706-c13e-412d-b6cf-270b944a4779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> css-1yxc0mn-option</value>
      <webElementGuid>4b923b2f-3ffe-4add-af36-c0f84bffc555</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-7-option-1</value>
      <webElementGuid>b23c2cf3-3981-46aa-a0dd-37c7cd94fed0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>6bf54a0c-afb1-4267-b3e6-eab88f21116d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Тестовая услуга два</value>
      <webElementGuid>dd198aa8-2524-4dba-a7d0-a8f387076c5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-7-option-1&quot;)</value>
      <webElementGuid>b793e82b-43d5-493c-b37b-dc6c0af82a2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-7-option-1']</value>
      <webElementGuid>4f26d2aa-4140-4868-ad3a-455b96aa40cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='drawer']/div[2]/div/div/div[2]/div/div/div/div/div/div[2]/div/div[2]</value>
      <webElementGuid>1a5a28db-159d-4aa1-8ed6-b38c8e8926ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Тестовая услуга'])[2]/following::div[1]</value>
      <webElementGuid>97509803-7296-46ac-a2e5-1c646580294e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Добавить услугу'])[1]/following::div[9]</value>
      <webElementGuid>a08f50ad-8501-4476-afdc-c389bc3a125a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Повторный приём'])[1]/preceding::div[1]</value>
      <webElementGuid>fc2a80e6-2628-4b73-87ce-93ddbb9c54b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QA test'])[1]/preceding::div[2]</value>
      <webElementGuid>5d4e268e-953b-4fef-9028-a2e816851983</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div[2]/div/div[2]</value>
      <webElementGuid>1edf9e99-7ec4-462e-b4a8-f2405ee2317e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-7-option-1' and (text() = 'Первчиный приём' or . = 'Первчиный приём')]</value>
      <webElementGuid>2fc52fa5-2549-4714-80fc-80e54ef20dc9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
