<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>3_usluga_vkladka</name>
   <tag></tag>
   <elementGuidId>b004e576-b5eb-435b-afd2-af049d701e95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class, 'container styles_container')]//p[text()='Тестовая услуга QA']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//p[(text() = 'Тестовая услуга QA' or . = 'Тестовая услуга QA')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#react-select-6-option-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>36fbe449-33c6-4bd4-9494-9c04d477bf03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> css-1yxc0mn-option</value>
      <webElementGuid>362122d7-7450-46c4-8d58-f7b77eb7b5ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-6-option-2</value>
      <webElementGuid>b3d5cc42-6e17-4fb6-8f16-a63f93362afb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>1664d99c-65c0-4c0c-89ca-ca684ed8f8d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Тестовая услуга QA</value>
      <webElementGuid>bfb81504-c5c4-4e7e-89f8-4f5620122b6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-6-option-2&quot;)</value>
      <webElementGuid>6ecc1f35-beb5-4383-9413-54713ee79431</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-6-option-2']</value>
      <webElementGuid>29d12f92-ebb5-4770-9472-694b3cc13696</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='drawer']/div[2]/div/div/div[2]/div/div/div/div/div/div[2]/div/div[3]</value>
      <webElementGuid>01a08d35-fd02-4625-97ca-e1751337b152</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Первчиный приём'])[2]/following::div[1]</value>
      <webElementGuid>60c9b19f-988a-4bfa-b7a6-0a578d05fd5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Тестовая услуга'])[2]/following::div[2]</value>
      <webElementGuid>ac95054c-16b1-4124-b453-6c50ab25b3b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Данная услуга уже добавлена'])[1]/preceding::div[1]</value>
      <webElementGuid>339ade43-bd61-45ad-afcd-99305ea048a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Сохранить'])[1]/preceding::div[3]</value>
      <webElementGuid>c4f9b0cc-2716-4b2a-a12d-6210eca0c67e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Повторный приём']/parent::*</value>
      <webElementGuid>dcf5852f-8e67-4a3e-87c2-69c5d775a6c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div[2]/div/div[3]</value>
      <webElementGuid>e1355d8d-14ca-4de5-9c49-73da7694e504</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-6-option-2' and (text() = 'Повторный приём' or . = 'Повторный приём')]</value>
      <webElementGuid>611f2250-be57-4c59-b9fe-5b091fb5812a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
