<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_first_time_in_kalendar</name>
   <tag></tag>
   <elementGuidId>1d101157-a978-4530-9bda-4d2c2856991c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type = 'button' and text() = '19:00']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.styles_time_button__s6QKa.styles_active__K9hl1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1d7936f4-d935-415b-8cd1-587598f2b346</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_time_button__s6QKa styles_active__K9hl1</value>
      <webElementGuid>1f43ec18-8e91-4a63-8b23-18f440c40ba1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>322fe531-bbc8-41b8-bab5-d23963ffb8cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>08:00</value>
      <webElementGuid>80841d3e-9e07-4e81-a75c-e3607df4b9aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;drawer&quot;)/div[@class=&quot;styles_wrapper__3fhNR&quot;]/div[@class=&quot;styles_wrapper__background__i5gz- styles_wrapper__background_active__1WfBI&quot;]/div[@class=&quot;styles_wrapper__content__3_KkI styles_wrapper__content_active__3cggn&quot;]/div[@class=&quot;styles_container__2wFx3&quot;]/div[@class=&quot;styles_content_container__3lD53&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;styles_container__2m6Fl&quot;]/div[@class=&quot;styles_container__1H_Vn&quot;]/div[@class=&quot;styles_hours_list__11YBr&quot;]/button[@class=&quot;styles_time_button__s6QKa styles_active__K9hl1&quot;]</value>
      <webElementGuid>e5e6a144-ebff-4e4b-8d3f-e324b17d7be5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>e6724ca4-219f-4da2-99f9-972d30a1e3ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>b1e65ab5-b8e6-4bba-a685-0d7c2b025590</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>33097e37-a219-4637-ad4a-c5371a480c6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>a5647895-b117-4f56-94d2-5e365839aca3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
