<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_data_current</name>
   <tag></tag>
   <elementGuidId>a7d7be2d-faa1-4d06-ae40-d70057e66529</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.styles_day__H2RjP.styles_day__active__3ZzgB.styles_day__current__1heXz</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[contains(@class, &quot;styles_day__current&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ce603270-71a0-42a7-9e48-88e92113d82a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>247e2e9e-7353-4dd5-8285-7f5d2f67ee45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_day__H2RjP styles_day__active__3ZzgB styles_day__current__1heXz</value>
      <webElementGuid>854c3016-2f30-49c2-b212-54e9b4bc76cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>21</value>
      <webElementGuid>4bb3e60f-8c11-468a-8cf1-0ad7f577b512</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;drawer&quot;)/div[@class=&quot;styles_wrapper__3fhNR&quot;]/div[@class=&quot;styles_wrapper__background__i5gz- styles_wrapper__background_active__1WfBI&quot;]/div[@class=&quot;styles_wrapper__content__3_KkI styles_wrapper__content_active__3cggn&quot;]/div[@class=&quot;styles_container__2wFx3&quot;]/div[@class=&quot;styles_content_container__3lD53&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;styles_container__2m6Fl&quot;]/div[@class=&quot;styles_container__DPERZ&quot;]/div[@class=&quot;styles_container__2Hqkg&quot;]/div[@class=&quot;styles_content__container__1CNvo&quot;]/button[@class=&quot;styles_day__H2RjP styles_day__active__3ZzgB styles_day__current__1heXz&quot;]</value>
      <webElementGuid>47f454b0-0233-4083-a9ba-cdf13b3fdafa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[39]</value>
      <webElementGuid>14f7fb83-b3bb-45fc-a52d-c8cb440e9d96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='drawer']/div[2]/div/div/div[2]/div/div[4]/div/div/div/div[2]/button[26]</value>
      <webElementGuid>c09fce19-dc19-4025-bf77-e393d38d1812</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Время приема'])[1]/following::button[28]</value>
      <webElementGuid>f3774742-4f58-47d3-882e-28bba44153cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='–'])[1]/preceding::button[17]</value>
      <webElementGuid>031ca753-20e5-4305-9f13-89aea1bfbf5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[1]/preceding::button[18]</value>
      <webElementGuid>78b57267-7b4a-4975-b009-e1523cc4c3a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='21']/parent::*</value>
      <webElementGuid>7a410065-8250-43de-ac4e-bd7a751cab5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[26]</value>
      <webElementGuid>19661e12-fbf7-4278-96ae-5fd54b0940aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '21' or . = '21')]</value>
      <webElementGuid>a0423bb1-3c4c-4174-b863-814eb38cd7b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
