<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cel_vizita_redactor</name>
   <tag></tag>
   <elementGuidId>60663e99-6ff8-45c6-bf0f-ff70c3be3dab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ivnlC-9rC41PeJYAJo3jr</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[3]/div[2]/div/div/div[2]/div[1]/div[5]/div/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>8280ca14-f0d4-4f4b-9562-baff4c8996b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>af0d1d7d-f1ef-491e-8c8d-f22c7e7a0386</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ivnlC-9rC41PeJYAJo3jr</value>
      <webElementGuid>e32f4026-729b-497d-bb1a-2f43f845a62a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1ce6ba9c-1975-40be-b3b8-f30cb6320053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input styles_textarea__3FuFL</value>
      <webElementGuid>5df4babb-a94b-4b22-a547-475cbc7b520a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Автотест. Цель визита редактирование</value>
      <webElementGuid>20bf26fe-5dcc-4907-966c-49532602c347</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ivnlC-9rC41PeJYAJo3jr&quot;)</value>
      <webElementGuid>df244209-649e-43ec-98e4-7a352dc0e4a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='ivnlC-9rC41PeJYAJo3jr']</value>
      <webElementGuid>8a995b81-eaeb-409e-b25c-490a5ed9214b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='drawer']/div[2]/div/div/div[2]/div[4]/div/textarea</value>
      <webElementGuid>9343b3df-b526-4b8a-8d0c-4684f0e9375f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Другое'])[1]/following::textarea[1]</value>
      <webElementGuid>f42c631f-2c95-4817-9a59-51b58a9648d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='По'])[1]/following::textarea[1]</value>
      <webElementGuid>8ae531bb-a713-41a8-835d-91d7ea9c9b97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Цель визита'])[2]/preceding::textarea[1]</value>
      <webElementGuid>71f9bba2-b963-439a-b319-f949ec20eb37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Отмена'])[1]/preceding::textarea[1]</value>
      <webElementGuid>42e73cb4-4002-485d-870b-a18a1e29f43d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Автотест. Цель визита редактирование']/parent::*</value>
      <webElementGuid>aee15902-8339-43d6-8422-ce58e8fa5332</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>adf8c368-8bbc-4bb6-b0d4-45154a2040bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'ivnlC-9rC41PeJYAJo3jr' and (text() = 'Автотест. Цель визита редактирование' or . = 'Автотест. Цель визита редактирование')]</value>
      <webElementGuid>1a6e4891-463a-41c4-ba54-6226332ef3bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
