<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cel_vizita_redactor</name>
   <tag></tag>
   <elementGuidId>60663e99-6ff8-45c6-bf0f-ff70c3be3dab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='drawer']/div[2]/div/div/div[2]/div[5]/div/textarea</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ivnlC-9rC41PeJYAJo3jr</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>fc687c2b-ec57-4852-ba2d-3d66a0ee2079</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>bf592916-5754-4eef-a171-983bf42ba0e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ivnlC-9rC41PeJYAJo3jr</value>
      <webElementGuid>ed595442-9aa9-4cd9-b29b-de83e36235ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4e9154aa-ab44-4498-8ca5-269cb7e1146c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input styles_textarea__3FuFL</value>
      <webElementGuid>6ce0d89c-4569-4ba2-8027-5438e06399f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Автотест. Цель визита редактирование</value>
      <webElementGuid>306cf388-8227-4e42-9a15-1e39acfd7f9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ivnlC-9rC41PeJYAJo3jr&quot;)</value>
      <webElementGuid>f2f3dc38-e682-4e3d-b442-2010965ac1b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='ivnlC-9rC41PeJYAJo3jr']</value>
      <webElementGuid>469b8568-7483-4af2-a78f-a18243e269cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='drawer']/div[2]/div/div/div[2]/div[4]/div/textarea</value>
      <webElementGuid>1339ce07-5c62-422f-b37f-182fc4b26082</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Другое'])[1]/following::textarea[1]</value>
      <webElementGuid>a9c21cb3-81bd-4139-b240-8b76bbca83ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='По'])[1]/following::textarea[1]</value>
      <webElementGuid>637ae71c-0fa2-4658-b7af-fec9cd8c8a1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Цель визита'])[2]/preceding::textarea[1]</value>
      <webElementGuid>98a933be-a6b5-4deb-8990-e6f464a29ffb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Отмена'])[1]/preceding::textarea[1]</value>
      <webElementGuid>652a25a6-2bdc-432b-80f5-c0025a848389</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Автотест. Цель визита редактирование']/parent::*</value>
      <webElementGuid>00dc1b72-2524-4785-a78a-583622263eff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>2f50c25c-dc63-4c38-8fc6-e8a780780052</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'ivnlC-9rC41PeJYAJo3jr' and (text() = 'Автотест. Цель визита редактирование' or . = 'Автотест. Цель визита редактирование')]</value>
      <webElementGuid>4571b82b-6dc1-40f6-8ea6-d97018e505bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
