<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verif_all_summ_time_uslug_vkladka</name>
   <tag></tag>
   <elementGuidId>56de4ec8-e617-44e2-93c2-13b5d15e4671</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[contains(@class, styles_content__header_title) and text()='Редактировать услуги']/following::p[contains(@class, 'styles_title') and text() = 'Итого']/following::p[@class='duration' and .='70 мин.']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.styles_wrapper__37S9J > div.styles_container__1LJOL > p.duration</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>dd59ad58-c8e1-4657-8eed-11d39a63007e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>duration</value>
      <webElementGuid>b3eb8dbc-be42-44bd-ac9f-11b29a8fe95a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>70 мин.</value>
      <webElementGuid>0088c0ca-e45b-43ba-8c47-840d31505473</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;drawer&quot;)/div[@class=&quot;styles_wrapper__3fhNR&quot;]/div[@class=&quot;styles_wrapper__background__i5gz- styles_wrapper__background_active__1WfBI&quot;]/div[@class=&quot;styles_wrapper__content__3_KkI styles_wrapper__content_active__3cggn&quot;]/div[@class=&quot;styles_container__1J0HH&quot;]/div[@class=&quot;styles_wrapper__37S9J&quot;]/div[@class=&quot;styles_container__1LJOL&quot;]/p[@class=&quot;duration&quot;]</value>
      <webElementGuid>cf04f8dd-7049-47d8-8bb5-6aa0e8510bfc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='drawer']/div[2]/div/div/div[2]/div/div[2]/p[2]</value>
      <webElementGuid>7fbcdf33-a919-4c42-b2da-9acf1ad28fd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Добавить услугу'])[1]/following::p[8]</value>
      <webElementGuid>b8ff62b4-8f6f-48fb-95f3-88a854d96007</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Редактировать'])[1]/following::p[9]</value>
      <webElementGuid>fb47686c-f6b8-4b81-9870-45811261edd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Сохранить'])[1]/preceding::p[2]</value>
      <webElementGuid>7beadc1f-9ec1-4a2c-a607-d6c9a78acffc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Отмена'])[1]/preceding::p[2]</value>
      <webElementGuid>5f3335cf-b31b-42ad-8655-d524a3c7f699</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='70']/parent::*</value>
      <webElementGuid>3edc6127-ab5a-4b35-aa06-e4b1444910e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div[2]/p[2]</value>
      <webElementGuid>e9ccf0d8-de0f-4322-b118-175e556388f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '70 мин.' or . = '70 мин.')]</value>
      <webElementGuid>0dd56290-dd92-424e-b3a1-16efa779fbf1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
