<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verif_delete_uslugi_vkladka_</name>
   <tag></tag>
   <elementGuidId>4c0da455-d8af-4f10-9d04-9bbfbe4c9ed5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[(text() = 'Тестовая услуга20 мин.1 000 ₽' or . = 'Тестовая услуга20 мин.1 000 ₽')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.styles_container__2rd2F</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[(text() = 'Тестовая услуга20 мин.1 000 ₽' or . = 'Тестовая услуга20 мин.1 000 ₽')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e7e066ea-fb0a-482a-9872-f60e267f4219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_container__2rd2F</value>
      <webElementGuid>b00bb33f-2da8-4bad-a024-3c65b47a8267</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Тестовая услуга20 мин.1 000 ₽</value>
      <webElementGuid>847c2e3e-0a22-4866-a433-29643c5bc9f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;drawer&quot;)/div[@class=&quot;styles_wrapper__3fhNR&quot;]/div[@class=&quot;styles_wrapper__background__i5gz- styles_wrapper__background_active__1WfBI&quot;]/div[@class=&quot;styles_wrapper__content__3_KkI styles_wrapper__content_active__3cggn&quot;]/div[@class=&quot;styles_container__1J0HH&quot;]/div[@class=&quot;styles_wrapper__37S9J&quot;]/div[@class=&quot;styles_container__A8wTi&quot;]/div[@class=&quot;styles_container__2rd2F&quot;]</value>
      <webElementGuid>9e1e792b-8bce-4315-955d-5559c230b91e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='drawer']/div[2]/div/div/div[2]/div/div/div[2]</value>
      <webElementGuid>9167892b-25e3-44c8-8a9c-181a83a3e9e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Добавить услугу'])[1]/following::div[6]</value>
      <webElementGuid>1c5771db-0f24-4d3c-b70e-9601b5ff2b9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Редактировать'])[1]/following::div[19]</value>
      <webElementGuid>737dec2e-6a97-4a16-9922-1dd8982b6d2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Сохранить'])[1]/preceding::div[3]</value>
      <webElementGuid>546bf6fd-f5a0-4565-aa46-73f279defe89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Отмена'])[1]/preceding::div[3]</value>
      <webElementGuid>f992041f-c711-4559-8acc-0427d4242e15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div[2]/div/div/div[2]</value>
      <webElementGuid>4b14ee51-28e3-4d09-87d5-1b99d332dd03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Тестовая услуга20 мин.1 000 ₽' or . = 'Тестовая услуга20 мин.1 000 ₽')]</value>
      <webElementGuid>ba7513e4-f1c0-4541-91f5-ebd7d1e377a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
