<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verif_familia_redactor_obshee</name>
   <tag></tag>
   <elementGuidId>9b3fcb59-2403-46a8-bb46-aa23e7160137</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fP5kvB58caCryfRMaU6s3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[3]/div[2]/div/div/div[2]/div[1]/div/div[1]/div/label/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b24ed4f3-65dd-44fa-b6c1-e45dc2585410</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fP5kvB58caCryfRMaU6s3</value>
      <webElementGuid>29b0be0e-d2eb-46d6-8c96-2f305f7d1d13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_input__Xf-yT</value>
      <webElementGuid>2d775b05-90e4-4345-971a-f9219975d336</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5efe3944-e709-4939-b56c-eca2398ffbf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>95463237-cdba-4f94-af81-aee62d7fd66f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fP5kvB58caCryfRMaU6s3&quot;)</value>
      <webElementGuid>60a4e87b-852f-4bb1-9296-3b8ce40b7ab7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fP5kvB58caCryfRMaU6s3']</value>
      <webElementGuid>f0e76897-d13e-4121-9d0e-4afcb4f33af8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='drawer']/div[2]/div/div/div[2]/div/div/div/label/input</value>
      <webElementGuid>1dd210a4-9a1f-4598-a411-7cfd701dc872</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>312d1fff-b6db-4f16-9539-066a6976dc2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'fP5kvB58caCryfRMaU6s3']</value>
      <webElementGuid>45738ef0-64a6-4f32-a2ec-ed6ecfb582a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
