<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Vrach_in_priem</name>
   <tag></tag>
   <elementGuidId>c2075f6a-a3b3-42a8-a6bb-2e58049f87fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.doctor__name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[(text() = 'Измайлов Дмитрий Петрович' or . = 'Измайлов Дмитрий Петрович')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>5f8004b2-4d51-42d5-8799-0bcd80692445</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>doctor__name</value>
      <webElementGuid>0de9b2a5-4ab5-4aaf-811d-bceb6508a00b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Измайлов Дмитрий Петрович</value>
      <webElementGuid>76685dee-39d3-44b6-ac1d-79d0937a859a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;drawer&quot;)/div[@class=&quot;styles_wrapper__3fhNR&quot;]/div[@class=&quot;styles_wrapper__background__i5gz- styles_wrapper__background_active__1WfBI&quot;]/div[@class=&quot;styles_wrapper__content__3_KkI styles_wrapper__content_active__3cggn&quot;]/div[@class=&quot;styles_container__3ivyS&quot;]/div[@class=&quot;styles_container__1zr_3&quot;]/div[@class=&quot;styles_container__2L7dy&quot;]/div[@class=&quot;styles_container__18AaY&quot;]/div[@class=&quot;styles_content__container__1FikG&quot;]/div[@class=&quot;styles_content__1YTzU&quot;]/div[@class=&quot;styles_info__1xIDw&quot;]/p[@class=&quot;doctor__name&quot;]</value>
      <webElementGuid>6c481ca0-5e00-44ba-b0c1-30c8255a84ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='drawer']/div/div/div/div[2]/div/div[2]/div/div/div[2]/div[2]/p</value>
      <webElementGuid>832536a2-6d5a-40e7-b01a-3700aac74121</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Врач'])[1]/following::p[1]</value>
      <webElementGuid>7f3cdcb0-8677-4f91-bcfc-dc5b5951a951</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Дата и время'])[1]/following::p[1]</value>
      <webElementGuid>ff3a74bb-7a6d-465e-9ec9-7c5d6c2f4697</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Пациент'])[1]/preceding::p[2]</value>
      <webElementGuid>a96b1e1c-c6b5-431e-aa29-3abcfa2d0c5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Avtotest QA Regressovich'])[1]/preceding::p[2]</value>
      <webElementGuid>5aa45567-8962-4032-90a2-3fd5db066618</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Измайлов Дмитрий Петрович']/parent::*</value>
      <webElementGuid>939b57ab-62f7-4b80-89f7-463ee3c2ddfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/p</value>
      <webElementGuid>b2a3f927-ae5f-4c74-8923-0385ed771b0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Измайлов Дмитрий Петрович' or . = 'Измайлов Дмитрий Петрович')]</value>
      <webElementGuid>ed0e56bb-2694-483d-9323-c700d7189153</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
