<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>yslugi_button</name>
   <tag></tag>
   <elementGuidId>527369ee-4072-497a-b822-b774dd6b250e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rc-tabs-0-tab-services</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@role = 'tab' and (text() = 'Услуги')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>08b13788-f24b-4d94-9709-14eb9a8e1aec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>fa586112-86b0-4b56-8b5c-cbef926abfd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>06e9dfe8-bd40-467d-9c04-7705de6a99d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-tabs-tab-btn</value>
      <webElementGuid>64677c89-cb95-45f2-8411-d9bb9f3e2044</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>af6e60c6-0f3b-496e-a8ef-e5e7d5ca6493</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rc-tabs-0-tab-services</value>
      <webElementGuid>16e26ec1-5e08-4af6-b946-a560582fc5b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>rc-tabs-0-panel-services</value>
      <webElementGuid>5d4d9e8e-c879-4eb5-add6-1f4e7a5fe63d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Услуги</value>
      <webElementGuid>1ee201c4-3fd7-4877-beb6-5704454500ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-tabs-0-tab-services&quot;)</value>
      <webElementGuid>bfd84c24-7fbc-4add-8408-f249c20e4937</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>e6251661-7925-4510-8380-0fdc9e39e724</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>7a0b86c9-6870-499b-8dda-e34f4f38b4ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>f41151de-9f67-4973-a92f-8b037f6cf2da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'rc-tabs-0-tab-services' and (text() = 'Услуги' or . = 'Услуги')]</value>
      <webElementGuid>8f7b82e3-6611-4a17-8d7f-a57ecaadcda9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
