<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FIO acc</name>
   <tag></tag>
   <elementGuidId>bd0f9b8d-8a6c-4a98-b8df-a189833bfd23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.styles_profile__username__QTKa4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header']/div/div[3]/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>43e0fa54-6c31-457d-99c8-234a8895a481</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_profile__username__QTKa4</value>
      <webElementGuid>ecfa7986-7730-4871-ac06-9d05730e26ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Тестовая клиника Совы  </value>
      <webElementGuid>1c3afc8a-e98e-4e98-9316-804d17401be1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;styles_header__container__YCgbf styles_header__container_admin__211f3&quot;]/div[@class=&quot;styles_header__gridElement__3-fjS styles_header__profile__Yq-8e&quot;]/div[@class=&quot;styles_profile__container__Lau6F styles_profile__popover__37-3V&quot;]/div[@class=&quot;styles_profile__username_wrapper__HSI87&quot;]/span[@class=&quot;styles_profile__username__QTKa4&quot;]</value>
      <webElementGuid>a3a31507-6413-4e39-9560-0e060ad45c1f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>b5a7e7a8-b455-4796-a37d-2129c49ffbfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>ad184440-653e-4c31-b830-950f9a6233b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>44f59061-acc8-4bee-8902-292dfca8c2b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>1d6f6204-45a0-4176-8323-261fdae05478</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>e63c241c-ce8a-4c62-aca4-c1b23c604e4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>a7ffb6cc-7782-4ffb-af41-9bfce674b5d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
