<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tab_status_otmena</name>
   <tag></tag>
   <elementGuidId>88f55adb-d954-43b7-9807-62e6b46ca8ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='Отменен']/parent::*</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#react-select-26-option-3</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[@class = ' css-1d0biql-option' and (text() = 'Отменен' or . = 'Отменен')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>98b5ab6c-0b3d-4416-b870-b01b9c267239</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> css-1d0biql-option</value>
      <webElementGuid>a9b324f1-80be-4f7a-9861-4352813aea2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-26-option-3</value>
      <webElementGuid>be671597-a208-4327-8f5b-aaf8ce244e68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>af49f5d1-91e0-4abb-b10d-5c9c3a2ea633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Отменен</value>
      <webElementGuid>ff900346-da48-421e-b04a-1120822685d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-26-option-3&quot;)</value>
      <webElementGuid>b5bce81c-afec-47bf-ae23-ec1fd4761600</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-26-option-3']</value>
      <webElementGuid>cf9d1ab3-e78d-4831-9943-e79592ac6fa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='drawer']/div/div/div/div[2]/div/div[3]/div/div/div/div[2]/div/div[4]</value>
      <webElementGuid>24030304-e5af-4be0-b7e3-f23e1a0be205</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Выполнен'])[1]/following::div[1]</value>
      <webElementGuid>59e872a3-5016-41cf-a76c-2fa51b4855b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Подтвержден'])[1]/following::div[2]</value>
      <webElementGuid>69e3749c-f0da-4c72-ba98-d116839678cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Редактировать'])[1]/preceding::div[1]</value>
      <webElementGuid>f67d775e-ec81-49f1-a728-2f4d4e65475c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Выйти'])[1]/preceding::div[2]</value>
      <webElementGuid>5fd20a95-e4d6-4cca-8892-37c95543988e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Отменен']/parent::*</value>
      <webElementGuid>0a49b9fc-bc0e-4d5c-ab34-819b79b1d189</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[4]</value>
      <webElementGuid>5896c227-622d-4605-b21f-0e0a88fcd6a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-26-option-3' and (text() = 'Отменен' or . = 'Отменен')]</value>
      <webElementGuid>ae96e236-7254-4846-9d84-2d1ac877a16c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
