<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tab_status_otmena</name>
   <tag></tag>
   <elementGuidId>88f55adb-d954-43b7-9807-62e6b46ca8ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[text() = 'Отменен']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[(text() = 'Отменен' or . = 'Отменен')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#react-select-26-option-3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3ea0f057-5b9b-45b0-917d-e9e627c66918</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> css-1d0biql-option</value>
      <webElementGuid>eebea237-ccda-4171-90eb-6929e4afc23f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-26-option-3</value>
      <webElementGuid>52c55be5-48ac-416e-a8e8-1a4399a97259</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>d505712b-cc97-4bf4-94cb-5fcb57a08a8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Отменен</value>
      <webElementGuid>7d817ff2-d1f8-4cf7-ae60-5b5b8f04a2ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-26-option-3&quot;)</value>
      <webElementGuid>f42af807-9020-4182-bf15-cc2f0751d83e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-26-option-3']</value>
      <webElementGuid>71750ba8-6505-496d-8ed0-8deb9a993af5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='drawer']/div/div/div/div[2]/div/div[3]/div/div/div/div[2]/div/div[4]</value>
      <webElementGuid>acf43ca7-4c91-404f-8e14-d6707f5f7d75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Выполнен'])[1]/following::div[1]</value>
      <webElementGuid>a4848fe5-30e7-41c4-9f8f-9461225e939c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Подтвержден'])[1]/following::div[2]</value>
      <webElementGuid>33dbd0f4-5061-4348-a990-2154ad32133c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Редактировать'])[1]/preceding::div[1]</value>
      <webElementGuid>bf2d6fd8-1799-4dbc-804d-234bae8abc42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Выйти'])[1]/preceding::div[2]</value>
      <webElementGuid>4938c77c-19ef-48c5-b09c-e0af04d15d76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Отменен']/parent::*</value>
      <webElementGuid>d5155982-2661-4cc4-b0ed-08c860eb086c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[4]</value>
      <webElementGuid>3c49266a-22de-4130-9998-2d12128c8f06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-26-option-3' and (text() = 'Отменен' or . = 'Отменен')]</value>
      <webElementGuid>cafc6865-67d8-42e8-a131-4da49888466b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
