<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verif_absolutely_delete_patient</name>
   <tag></tag>
   <elementGuidId>dcda2875-48f8-4e74-afa2-fb637a470e1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/main/section/div/div[3]/div/div[2]/div/div/h3</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>71ae02d8-dc13-4794-b0ae-6d0776c73b45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>НИЧЕГО НЕ НАЙДЕНО</value>
      <webElementGuid>b1b90e49-4947-46cb-9a2e-97b9291c8a59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;styles_layout__wrapper__2zeB1&quot;]/div[@class=&quot;styles_layout__container__3D3Vr styles_layout__container_admin__2X_qx&quot;]/main[@class=&quot;styles_layout__content__1BAJN styles_layout__content_admin__WVT00&quot;]/section[@class=&quot;styles_contentLayout__1rqiW&quot;]/div[@class=&quot;styles_container__1MkwW&quot;]/div[@class=&quot;table-container&quot;]/div[@class=&quot;styles_table-wrapper__3zrY3&quot;]/div[@class=&quot;styles_table-container__inner__3Iilq&quot;]/div[@class=&quot;styles_plug_container__1rCwu&quot;]/div[@class=&quot;styles_plug_container__inner__30QB_&quot;]/h3[1]</value>
      <webElementGuid>35be88d9-d4fc-489d-b640-1a7956b4aae9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/main/section/div/div[3]/div/div[2]/div/div/h3</value>
      <webElementGuid>a315ada6-189e-4c16-a713-923993609d4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Дата рождения'])[1]/following::h3[1]</value>
      <webElementGuid>097086e1-6b67-4775-9b02-cbefc4d144b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Номер телефона'])[1]/following::h3[1]</value>
      <webElementGuid>6d290b9b-ecd3-4f02-b9a3-27def29e166f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='НИЧЕГО НЕ НАЙДЕНО']/parent::*</value>
      <webElementGuid>3044a82f-08d3-45ac-8cea-16168dedba2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3</value>
      <webElementGuid>35080f76-5fd3-4aa2-b146-f83b17bc0871</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'НИЧЕГО НЕ НАЙДЕНО' or . = 'НИЧЕГО НЕ НАЙДЕНО')]</value>
      <webElementGuid>14c7fd5e-aeec-4271-b8e0-d9cdf77607a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
