<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verif_email</name>
   <tag></tag>
   <elementGuidId>b20ce772-ef0a-4831-9fb5-b48b191d3317</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;LtW-eJBGrXyS2l37j7_3-&quot;)[count(. | //input[@id = 'LtW-eJBGrXyS2l37j7_3-' and @type = 'text']) = count(//input[@id = 'LtW-eJBGrXyS2l37j7_3-' and @type = 'text'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#LtW-eJBGrXyS2l37j7_3-</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;nXc7h9SqsTi9INJG8DKlF&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2d41b1be-7c0b-420f-b8ba-7ad77f3ca8dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LtW-eJBGrXyS2l37j7_3-</value>
      <webElementGuid>6293dc26-194c-47e9-a026-26c430398586</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_input__Xf-yT styles_field__2KsgS styles_field__231__3U3JZ</value>
      <webElementGuid>834ad33f-484d-415c-b220-8946cc8a0bcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8a81ef25-8188-4c03-a666-45b5977670f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2db062e8-9c96-4666-9828-28436642ef8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>AvtotestQA@mail.ru</value>
      <webElementGuid>2f3b5361-fca0-42d1-a592-2e6dcf15022e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LtW-eJBGrXyS2l37j7_3-&quot;)</value>
      <webElementGuid>cf8b3832-8e99-4371-9db2-90577ba46216</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='LtW-eJBGrXyS2l37j7_3-']</value>
      <webElementGuid>fd2e7415-258a-4aa4-8520-458f8196dd07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/main/section/div[2]/div[2]/form/div[2]/div/label/input</value>
      <webElementGuid>0251bd16-2dc1-4dc8-be26-685f773e0004</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/label/input</value>
      <webElementGuid>bdd23011-1018-4109-9553-a0d261ae9a72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'LtW-eJBGrXyS2l37j7_3-' and @type = 'text']</value>
      <webElementGuid>68197117-3edb-4599-b4a8-7960e0b50885</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
