<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__name_ysluga_in_modal_add</name>
   <tag></tag>
   <elementGuidId>cf1aa1fd-4f62-45d6-b845-68eaa58982c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='drawer']/div/div/div/form/div/div/div/label/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DiDhlB2gFWqVzfg0a0kK5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5f79cf5d-f27f-4ed4-9148-ddfa72147dbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DiDhlB2gFWqVzfg0a0kK5</value>
      <webElementGuid>f6eeaa68-1332-42f6-a8d9-6a98d90d325f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_input__Xf-yT</value>
      <webElementGuid>8f712ac5-625f-4fac-b654-542c771f1c99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4c964731-3c35-4a56-bb70-f26a7f31cd72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Т</value>
      <webElementGuid>e794063b-899c-467e-afbd-927771f9d779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DiDhlB2gFWqVzfg0a0kK5&quot;)</value>
      <webElementGuid>25bf0e2a-eb7c-423e-95ec-d9ac24f5d157</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DiDhlB2gFWqVzfg0a0kK5']</value>
      <webElementGuid>65bf6c50-41ae-45d7-a3b8-ccd23ac6d9db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='drawer']/div/div/div/form/div/div/div/label/input</value>
      <webElementGuid>63c16df6-10ad-4de1-a9f2-1a6fb8d5d267</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>656c105a-2c2d-48cb-8693-9d195300ef7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'DiDhlB2gFWqVzfg0a0kK5']</value>
      <webElementGuid>5bb64b4b-f306-41df-b2f8-487a522aa2bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
