<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__kod_ysluga_add_in_ modal</name>
   <tag></tag>
   <elementGuidId>b40bffa2-f9b6-491e-bf1d-ded61d3eadac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='drawer']/div/div/div/form/div/div/div[2]/label/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#j-iggObfaJ9umKGIIpmbt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a1c96677-6a28-455d-9d9b-0159bfa6c366</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>j-iggObfaJ9umKGIIpmbt</value>
      <webElementGuid>c02bd23b-d014-4a4d-98b1-6e13d4b3a93e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_input__Xf-yT</value>
      <webElementGuid>89093a9a-a533-44a9-9640-a2c1ea22e1be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>53b51697-afe2-4889-8b19-834252b9ada7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>5a3b9f4a-9de1-41de-b1e2-2b16497b252d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;j-iggObfaJ9umKGIIpmbt&quot;)</value>
      <webElementGuid>0be79eb9-6d88-443f-8bba-72c83da0b26c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='j-iggObfaJ9umKGIIpmbt']</value>
      <webElementGuid>a881d1ce-6819-4506-9fc5-1d2a8ae6efd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='drawer']/div/div/div/form/div/div/div[2]/label/input</value>
      <webElementGuid>722c311e-7f70-4d90-8f01-65e5f2d423fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label/input</value>
      <webElementGuid>04d70a87-4131-4721-abe5-4140adbd08f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'j-iggObfaJ9umKGIIpmbt']</value>
      <webElementGuid>2f78584d-f904-4a44-922d-9588c2077950</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
