<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__name_edit_ysluga</name>
   <tag></tag>
   <elementGuidId>7e9e9012-dbbb-43bf-a513-3a51346880a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[4]/div/div[3]/div/div/div[2]/form/div[1]/div/div[1]/label/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ZIhyeczWUiPKzOTYKkGmC</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>19589f7b-0905-41fa-b4c1-4628516b30dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ZIhyeczWUiPKzOTYKkGmC</value>
      <webElementGuid>0d99b1b1-102c-444f-94fe-cc27131508eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_input__Xf-yT</value>
      <webElementGuid>e3428fc3-b743-48a5-a3ef-e662dc6891d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6212e4e5-ee70-4bb9-8fb0-dff98c7caa9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Тестовая услуга QA два</value>
      <webElementGuid>b617c63c-c79e-4f38-9824-db06c307d552</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ZIhyeczWUiPKzOTYKkGmC&quot;)</value>
      <webElementGuid>812a2e5a-0b92-4393-8159-2adbf2fd79dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ZIhyeczWUiPKzOTYKkGmC']</value>
      <webElementGuid>0028a423-e64c-4940-869f-54aaddc7a6f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>f64e0f8f-5a92-4753-af5f-4d06ba65f728</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ZIhyeczWUiPKzOTYKkGmC']</value>
      <webElementGuid>96de43a5-6205-4aa6-a64b-226feeb9de77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
