<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__kog_edit_sluga</name>
   <tag></tag>
   <elementGuidId>dfcb20e6-4d86-4447-b20d-dcc131e98ea9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[4]/div/div[3]/div/div/div[2]/form/div[1]/div/div[2]/label/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Zh0I9q0-qqGgcybQ8zQ2A</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0ecbefa6-cf98-42f9-afba-fe425db9056b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Zh0I9q0-qqGgcybQ8zQ2A</value>
      <webElementGuid>32d2636e-c6d2-4dd0-84d6-0d7f63169950</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_input__Xf-yT</value>
      <webElementGuid>026f543e-3f8b-4860-8540-d05f9fcc7bd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4ea13c7b-1954-4559-84cb-bee53be73764</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Zh0I9q0-qqGgcybQ8zQ2A&quot;)</value>
      <webElementGuid>642441e1-7398-4e07-a0d7-73b9cf6d81d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Zh0I9q0-qqGgcybQ8zQ2A']</value>
      <webElementGuid>7e39f8f0-ade3-46c5-84ca-438e5635a606</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label/input</value>
      <webElementGuid>16d4a0ae-5ebb-4923-a6ce-dbd31f6ebf5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Zh0I9q0-qqGgcybQ8zQ2A']</value>
      <webElementGuid>43d8ac06-d484-4ef2-8e60-40fe7783f95c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
