<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dlitelnost_in_multiselect_yslugi</name>
   <tag></tag>
   <elementGuidId>9acac40b-ae0f-41f9-bc8b-68643af9b742</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[(text() = '50 мин.' or . = '50 мин.')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>73965fd1-8301-4bf3-b8d8-1c6e16714ef7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>duration</value>
      <webElementGuid>d7ca7654-91aa-4767-9019-23710492afaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>132 мин.</value>
      <webElementGuid>94713c39-67b1-4214-ae49-ecb91e2eb57c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;drawer&quot;)/div[@class=&quot;styles_wrapper__3fhNR&quot;]/div[@class=&quot;styles_wrapper__background__i5gz- styles_wrapper__background_active__1WfBI&quot;]/div[@class=&quot;styles_wrapper__content__3_KkI styles_wrapper__content_active__3cggn&quot;]/div[@class=&quot;styles_container__1J0HH&quot;]/div[@class=&quot;styles_wrapper__12tXl&quot;]/div[@class=&quot;styles_container__2gakB&quot;]/div[@class=&quot;styles_selectInputContainer__1vEHJ&quot;]/div[@class=&quot;styles_selectInputWrapper__p580E&quot;]/div[@class=&quot;css-dyr6gj-container&quot;]/div[@class=&quot;css-5v18ew-menu&quot;]/div[@class=&quot;container styles_container__21Xd7&quot;]/div[@class=&quot;styles_service__item__3nXFY&quot;]/p[@class=&quot;duration&quot;]</value>
      <webElementGuid>6b711481-9d6d-43d3-bd6e-a2ceb09187f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='drawer']/div[2]/div/div/div[2]/div/div/div/div/div/div[2]/div/div[6]/p[3]</value>
      <webElementGuid>186fff55-3c3b-4237-9bc4-b31b5fd32dd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Добавить услугу'])[1]/following::p[15]</value>
      <webElementGuid>fc1d969b-0218-48e9-b9b2-b1c187695eca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Редактировать'])[1]/following::p[16]</value>
      <webElementGuid>ab7f7f30-43eb-4081-917b-4c2a4d7b3cad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Сохранить'])[1]/preceding::p[22]</value>
      <webElementGuid>3d6a76da-0586-4e76-8d03-de789c321c8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Отмена'])[1]/preceding::p[22]</value>
      <webElementGuid>946080ec-8cf0-4f04-ac79-cc27b375b0c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='132']/parent::*</value>
      <webElementGuid>6fcc5d17-0096-42b4-9de1-958a904b35ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/p[3]</value>
      <webElementGuid>7b26bb1f-5705-49c7-8d6c-c3bb25769ca0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '132 мин.' or . = '132 мин.')]</value>
      <webElementGuid>dab4907d-edcf-401c-893a-ff33ba9bbb31</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
