<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verif_name_on_modal_filial</name>
   <tag></tag>
   <elementGuidId>f0a32e2d-6a3a-4168-8af2-bdf041fdfe21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='drawer']/div/div/div/div[2]/div[2]/div/div[2]/div/p[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.styles_table__template__1hO5d.styles_table__template__1YhBQ.styles_service__item__2ClIM > p.styles_name__21UOF.styles_name__21UOF</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>a85e0ecd-6107-494f-87b2-dd6606bf41e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_name__21UOF styles_name__21UOF</value>
      <webElementGuid>51e4fc88-207f-44fa-b125-d363359598ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Тестовая услуга два</value>
      <webElementGuid>46107d92-a6e9-41c4-9a91-8da3e9631685</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;drawer&quot;)/div[@class=&quot;styles_wrapper__3fhNR&quot;]/div[@class=&quot;styles_wrapper__background__i5gz- styles_wrapper__background_active__1WfBI&quot;]/div[@class=&quot;styles_wrapper__content__3_KkI styles_wrapper__content_active__3cggn&quot;]/div[@class=&quot;styles_container__2VOdc&quot;]/div[@class=&quot;styles_table__container__2Xqgx&quot;]/div[@class=&quot;container&quot;]/div[2]/div[@class=&quot;styles_table__template__1hO5d styles_table__template__1YhBQ styles_service__item__2ClIM&quot;]/p[@class=&quot;styles_name__21UOF styles_name__21UOF&quot;]</value>
      <webElementGuid>ac85aac1-2de8-4ad5-89ed-c30366923cbe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='drawer']/div/div/div/div[2]/div[2]/div/div[2]/div/p[2]</value>
      <webElementGuid>b6dcdd67-44d6-45e3-b8d8-a27a7144197a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Автотест'])[1]/following::p[31]</value>
      <webElementGuid>6a71363b-2347-4cde-999c-7454b9f3b6ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+ Добавить услугу'])[1]/following::p[31]</value>
      <webElementGuid>37500444-c8f5-4b6f-9458-158ff4afd716</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Добавлена к филиалу'])[1]/preceding::p[1]</value>
      <webElementGuid>2ab6787c-dcff-426b-b824-8c425e71af59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]/div/p[2]</value>
      <webElementGuid>b0b1d887-a974-4ac9-9828-84f149125907</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Тестовая услуга два' or . = 'Тестовая услуга два')]</value>
      <webElementGuid>787bc02a-6a16-43d0-9366-97a4017f97cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
