<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>vkladka_yslugi_filialov</name>
   <tag></tag>
   <elementGuidId>9e88cd6d-66dc-4080-b5c0-890e1021b5a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id = 'rc-tabs-0-tab-/services/branch' and (text() = 'Услуги филиалов' or . = 'Услуги филиалов')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6a06e75d-fb0b-4837-bc5e-55585fc06385</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>3d144294-b21f-4b1a-b942-16e2fc0b2a70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>090d8735-9be9-4301-aa7b-cf8d6059040b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-tabs-tab-btn</value>
      <webElementGuid>cca797f2-4d6a-449f-aa8a-7e8db025b368</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>54de8de3-9f2c-46bd-b0e4-0b74bbfc62dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rc-tabs-0-tab-/services/branch</value>
      <webElementGuid>7c8d83bf-d7c6-4a9d-967b-1dcf6dafa9d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>rc-tabs-0-panel-/services/branch</value>
      <webElementGuid>111f1699-f3b5-4d88-93c3-d1d8745461d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Услуги филиалов</value>
      <webElementGuid>f5803b85-e867-45d3-a42e-6e186caca0d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-tabs-0-tab-/services/branch&quot;)</value>
      <webElementGuid>af93c30f-441e-4526-b034-e122aea5c190</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='rc-tabs-0-tab-/services/branch']</value>
      <webElementGuid>8e1bc31d-91b6-472a-86f6-81b0e2114fc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/main/section/div/div[2]/div/div/div/div[2]/div</value>
      <webElementGuid>667b3c6e-9b41-48f2-8931-1412da532d2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Каталог услуг'])[1]/following::div[2]</value>
      <webElementGuid>9b9cd467-13d9-4462-ad84-8afa8cb02b3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Услуги'])[2]/following::div[8]</value>
      <webElementGuid>4f7cbe64-dd02-464d-bf5b-cad1e2d760dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+ Добавить услугу'])[1]/preceding::div[6]</value>
      <webElementGuid>1d3ae88b-761d-433c-a55d-4a84aa3a21d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'rc-tabs-0-tab-/services/branch', '&quot;', ')')])[1]/preceding::div[28]</value>
      <webElementGuid>fcbcb770-537c-402d-ab04-738124b170d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Услуги филиалов']/parent::*</value>
      <webElementGuid>49d98927-f5de-41aa-8420-c9f3eb2ebc23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div</value>
      <webElementGuid>b1904028-5636-4330-b4f9-07c0e5b98aff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'rc-tabs-0-tab-/services/branch' and (text() = 'Услуги филиалов' or . = 'Услуги филиалов')]</value>
      <webElementGuid>2184a927-96ba-417f-b4a6-7833ef6c2673</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
