<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FIO acc</name>
   <tag></tag>
   <elementGuidId>a9ecca7c-eb2d-456b-9415-6a9435387850</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.styles_profile__username__QTKa4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header']/div/div[3]/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5d85821d-b5a5-499b-bd1e-4525403e390d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_profile__username__QTKa4</value>
      <webElementGuid>a059dc13-7d89-47ae-9634-4a433eadb8a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Тестовая клиника Совы  </value>
      <webElementGuid>2bf7a298-0502-47b1-946e-c1ffdb008c92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;styles_header__container__YCgbf styles_header__container_admin__211f3&quot;]/div[@class=&quot;styles_header__gridElement__3-fjS styles_header__profile__Yq-8e&quot;]/div[@class=&quot;styles_profile__container__Lau6F styles_profile__popover__37-3V&quot;]/div[@class=&quot;styles_profile__username_wrapper__HSI87&quot;]/span[@class=&quot;styles_profile__username__QTKa4&quot;]</value>
      <webElementGuid>90d90aae-f90d-47d8-b37d-5f9f05992eb1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>be89dac8-07ba-4f93-bfd1-88ccef6df082</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>ddb52e1a-c1ac-46dc-90ee-e0978d27a924</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>bbba76b3-e584-469b-bcb0-51535abe1987</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>84f6b631-4e38-4430-94a0-ca2df433fe1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>5ca7cef7-224a-4146-8f39-5a306dc2f3f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>7e4698e1-31c6-4d80-90c6-6ca166cf2d04</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
