<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>add_patient_information_card</name>
   <tag></tag>
   <elementGuidId>631491f8-c592-4855-ba57-a3d71ca094d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[(text() = 'Добавить пациента' or . = 'Добавить пациента')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.styles_selectContainer__2_EJI</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>159786d7-f603-43fc-a645-8a796cba9f91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_selectContainer__2_EJI</value>
      <webElementGuid>ef28f8b2-d556-476d-9efc-c5ee35f0567f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Добавить пациента</value>
      <webElementGuid>87b8de4a-bd34-4028-970e-07eb55f71224</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-6-option-0&quot;)/div[1]/div[@class=&quot;styles_selectContainer__2_EJI&quot;]</value>
      <webElementGuid>605142d9-708f-47c6-b72c-05887574039c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-select-6-option-0']/div/div</value>
      <webElementGuid>c2ff3157-6420-408c-ad09-26ed31d2ec60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='crea'])[1]/following::div[6]</value>
      <webElementGuid>ed3ce976-f19f-4558-ac94-b9049d1a0b69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Фамилия или номер телефона'])[1]/following::div[12]</value>
      <webElementGuid>2eda3307-12df-4027-b05f-5e8d9881956d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Имя'])[1]/preceding::div[1]</value>
      <webElementGuid>91f4c7ff-7da7-48ee-9794-962eb8d181e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Отчество'])[1]/preceding::div[2]</value>
      <webElementGuid>f666ff78-ba17-4425-b52d-78adee32394c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Добавить пациента']/parent::*</value>
      <webElementGuid>79759275-2722-4e5d-8b9b-a60e737b39d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div[2]/div/div/div/div</value>
      <webElementGuid>d8221cfb-61cc-45bf-922e-df3eee79e2c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Добавить пациента' or . = 'Добавить пациента')]</value>
      <webElementGuid>9ab26dd9-cbeb-4d3f-95b0-d4aa7e06a86e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
