<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h_specialist_name</name>
   <tag></tag>
   <elementGuidId>15d8e70c-cf5b-413e-a426-9d32e0119b15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h3[(text() = 'Машина М. Б.' or . = 'Машина М. Б.')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//h3[(text() = '${GlobalVariable.Test_vrach_abbreviaturoi}' or . = '${GlobalVariable.Test_vrach_abbreviaturoi}')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h3.styles_doctor__name__3d6ES</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>f9dc05a4-8033-4451-8095-aa1e5ad93e2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_doctor__name__3d6ES</value>
      <webElementGuid>dda3be64-d4bd-44e8-97f4-e5f74d98ad07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>${GlobalVariable.Test_vrach_abbreviaturoi}</value>
      <webElementGuid>1aa36b90-9121-4df7-8a6a-062bf9eaaa83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;styles_layout__wrapper__2zeB1&quot;]/div[@class=&quot;styles_layout__container__3D3Vr styles_layout__container_admin__2X_qx&quot;]/main[@class=&quot;styles_layout__content__1BAJN styles_layout__content_admin__WVT00&quot;]/section[@class=&quot;styles_contentLayout__1rqiW&quot;]/div[@class=&quot;container&quot;]/div[2]/div[@class=&quot;styles_appointmentList__tSlng&quot;]/div[@class=&quot;styles_appointmentList__table__1H_PX&quot;]/div[@class=&quot;styles_day__doctors__1b3VR&quot;]/div[@class=&quot;styles_doctor__3Qv0N&quot;]/div[@class=&quot;styles_doctor__info__1KgFp&quot;]/h3[@class=&quot;styles_doctor__name__3d6ES&quot;]</value>
      <webElementGuid>62385c79-aa01-43f3-8922-9b88b052762c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/main/section/div/div[2]/div[2]/div/div[2]/div/div/h3</value>
      <webElementGuid>2f5580f8-7d55-44fb-aeaf-ff34fdf594ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>fc0b0b8e-9684-42b1-91f7-69d55f49a53c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
