<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_cel_vizita</name>
   <tag></tag>
   <elementGuidId>45112f89-f5fd-4e20-bf7c-de9c6365b896</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='drawer']/div/div/div/form/div/div[5]/div/textarea</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ShWbRhnAdo4yMsHbG3g3a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>9ff9c988-10d6-4be8-b928-b0cbd242ae52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>c76997f7-f2f8-47ef-8712-799e4cb03e01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ShWbRhnAdo4yMsHbG3g3a</value>
      <webElementGuid>f0832711-92be-4527-8073-dd8ed01351cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f0b2b84c-7fd6-4abe-bed4-d714f14723e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input styles_textarea__3FuFL</value>
      <webElementGuid>9264edc8-de25-42d6-a58e-8077dd0d80e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Автотест. Цель визита</value>
      <webElementGuid>3bae91fc-34c2-4780-99f6-2bb1e577dc80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ShWbRhnAdo4yMsHbG3g3a&quot;)</value>
      <webElementGuid>c8813fbc-55bd-466e-b9a4-ed192dc31689</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='ShWbRhnAdo4yMsHbG3g3a']</value>
      <webElementGuid>f970a2fe-b467-4a2e-aaf7-a7d4a7b83a44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='drawer']/div/div/div/form/div/div[4]/div/textarea</value>
      <webElementGuid>a941baf0-eda3-465c-b2ef-118554a4fea2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Другое'])[1]/following::textarea[1]</value>
      <webElementGuid>9c0a5c24-261d-42cd-a8e8-9a897e7b1afd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='По'])[1]/following::textarea[1]</value>
      <webElementGuid>ccff53ee-c331-44b5-89b6-780811019a7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Цель визита'])[1]/preceding::textarea[1]</value>
      <webElementGuid>7f37cc64-c0be-410e-a9b3-127711779235</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Услуги'])[1]/preceding::textarea[1]</value>
      <webElementGuid>f7f938d9-ae4b-4c4d-816f-975559f52782</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Автотест. Цель визита']/parent::*</value>
      <webElementGuid>e60118b1-836e-4bae-b0e4-e03244b28381</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>9771327e-818a-4dc9-ac11-877b6c5e3013</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'ShWbRhnAdo4yMsHbG3g3a' and (text() = 'Автотест. Цель визита' or . = 'Автотест. Цель визита')]</value>
      <webElementGuid>db97f25a-d6df-4ebc-8800-52fe9e7e9a99</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
