<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__month</name>
   <tag></tag>
   <elementGuidId>b25af6bc-f4ae-4c3a-a806-7859da6db9c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='month'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.react-date-picker.react-date-picker--open.react-date-picker--enabled.custom_input_3j23dLnd2u9.custom_input_3j2wKdn3.styles_date_input__2LV4r.day_width_3fn123d213dg > div.react-date-picker__wrapper > div.react-date-picker__inputGroup > input[name=&quot;month&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>562c1c0e-b3ce-4d39-ace2-e9c5e15c9742</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>9f0aa012-902b-4399-a17d-d796fc134de1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>react-date-picker__inputGroup__input react-date-picker__inputGroup__month react-date-picker__inputGroup__input--hasLeadingZero</value>
      <webElementGuid>aabc2dd4-9e3e-451f-b13d-16104f4dbcde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-input</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>29cfd316-9cee-4c74-9a5f-0c46f232d696</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>c170495b-dad5-4c9e-86eb-b78332579578</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>5d0b44ed-97b1-479c-a882-432ed9569bd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>57aeb3a2-3e37-4c7d-89ff-5aff11b3da26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>month</value>
      <webElementGuid>867c19c3-695a-49e0-acfc-bd00ff239f15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>b6f81316-24e2-417e-b32e-5e8afcf4b1ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>f49b29d1-fe71-4688-9c94-a9a760e8c976</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;drawer&quot;)/div[@class=&quot;styles_wrapper__3fhNR&quot;]/div[@class=&quot;styles_wrapper__background__i5gz- styles_wrapper__background_active__1WfBI&quot;]/div[@class=&quot;styles_wrapper__content__3_KkI styles_wrapper__content_active__3cggn&quot;]/form[@class=&quot;styles_container__2kCJE&quot;]/div[@class=&quot;styles_content__container__20ZQn&quot;]/div[1]/div[@class=&quot;styles_patientData__container__2dYQk&quot;]/div[@class=&quot;styles_patientData__birthdate__3_Mzs&quot;]/div[@class=&quot;styles_container__4Xrq-&quot;]/div[@class=&quot;react-date-picker react-date-picker--open react-date-picker--enabled custom_input_3j23dLnd2u9 custom_input_3j2wKdn3 styles_date_input__2LV4r day_width_3fn123d213dg&quot;]/div[@class=&quot;react-date-picker__wrapper&quot;]/div[@class=&quot;react-date-picker__inputGroup&quot;]/input[@class=&quot;react-date-picker__inputGroup__input react-date-picker__inputGroup__month react-date-picker__inputGroup__input--hasLeadingZero&quot;]</value>
      <webElementGuid>4f0028a2-1154-47c7-9eae-57196288ca55</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='month'])[2]</value>
      <webElementGuid>875f468a-3d0f-45ed-ae87-48ed192e1f08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='drawer']/div/div/div/form/div/div/div/div[4]/div/div/div/div/input[3]</value>
      <webElementGuid>def06878-98f9-45ca-9fca-c7c7cd47f78a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/input[3]</value>
      <webElementGuid>eb32c90f-9537-4809-bc63-44f8e31dca01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'month' and @placeholder = '1' and @type = 'number']</value>
      <webElementGuid>4b3fa6b9-d684-4566-a640-2c0cdfc88161</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
