<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_otchestvo_in_infprmation</name>
   <tag></tag>
   <elementGuidId>4ac99609-c202-41e7-b029-9e57c8df286a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[3]/div/div/div/form/div[1]/div[1]/div/div[3]/div/label/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#_ID7EQMryP8r1aQOJce3h</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6bdf9750-81cd-4399-ad67-54e4fa4d8981</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_ID7EQMryP8r1aQOJce3h</value>
      <webElementGuid>940000cd-8c02-47c4-9aab-161083e7310f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_input__Xf-yT</value>
      <webElementGuid>a1364396-536f-403f-891d-02072db28df5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1400c538-9dcf-40ba-a0fc-83250a398a06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>control</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>8e72de8e-6b68-4b95-9519-7df9752d5bf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Т</value>
      <webElementGuid>b54d420a-c515-41b6-8f17-9b358b62c31e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_ID7EQMryP8r1aQOJce3h&quot;)</value>
      <webElementGuid>727fc838-f76d-43b0-9661-1ab320087c87</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='_ID7EQMryP8r1aQOJce3h']</value>
      <webElementGuid>f385f617-1836-4082-947c-ad0609c25ba5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='drawer']/div/div/div/form/div/div/div/div[3]/label/input</value>
      <webElementGuid>5f978846-554f-483f-a85d-fcf993f35946</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/label/input</value>
      <webElementGuid>3a31cea7-b299-4db5-a449-3a4bbb0c7c98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '_ID7EQMryP8r1aQOJce3h']</value>
      <webElementGuid>ea97af56-256c-4ccc-9b14-b5c4d8905a83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
