<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Name_in_information</name>
   <tag></tag>
   <elementGuidId>c748644a-8489-46c1-854d-68b148609e82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[3]/div/div/div/form/div[1]/div[1]/div/div[2]/div/label/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#aMY2qnTLDDA9zpw7DGa6a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>97f04d9c-4caa-43dd-8976-237910cbd6c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>aMY2qnTLDDA9zpw7DGa6a</value>
      <webElementGuid>d5d67917-1377-4253-ad42-bd6dabb9dfad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_input__Xf-yT</value>
      <webElementGuid>49b5b222-5e40-488f-8ca4-f21232e7cd09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6583a7bf-19ec-4f42-b861-683cfeb2aad8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>control</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>fbcad0ee-cea1-41b0-a446-86c1dd18daea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>З</value>
      <webElementGuid>dbdc7a54-6cf1-4679-bb54-22c0686353b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aMY2qnTLDDA9zpw7DGa6a&quot;)</value>
      <webElementGuid>bfe7d854-ed8a-4604-87b2-32b0516a4456</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='aMY2qnTLDDA9zpw7DGa6a']</value>
      <webElementGuid>05b7dfb1-3723-43ab-beab-d9c30c6d1502</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='drawer']/div/div/div/form/div/div/div/div[2]/label/input</value>
      <webElementGuid>da9458a0-b7c8-436e-8867-7a81e0a41245</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label/input</value>
      <webElementGuid>781b9b56-76ee-44a8-9025-608b88353fd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'aMY2qnTLDDA9zpw7DGa6a']</value>
      <webElementGuid>83bb8e4b-05db-42fc-ba61-33419a155ba7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
