<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>patient_card_Create P</name>
   <tag></tag>
   <elementGuidId>d5c9b256-1733-4d6b-a2c3-dbbd37ce9f98</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[(text() = 'Create P. Т.' or . = 'Create P. Т.')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '${GlobalVariable.Test_patient2_abbreviaturoi}' or . = '${GlobalVariable.Test_patient2_abbreviaturoi}')]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>96de38f3-2de4-434c-82cc-55c5157fc257</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>44a162ec-c208-422b-be26-ebf8b832fa2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>${GlobalVariable.Test_patient2_abbreviaturoi}</value>
      <webElementGuid>db5ee169-578a-4e94-9e2d-bb4ea368ed40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>3f1fb2ed-9434-4903-9269-c2cd8efdd5fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/main/section/div/div[2]/div[2]/div/div/div[2]/div[3]/div[2]/div[2]/div/div/div/p</value>
      <webElementGuid>2a3d5bf9-89dc-4471-8004-e022a670632c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Боевая М. М.'])[1]/following::p[4]</value>
      <webElementGuid>e29734c3-3c9d-4299-ac1d-dc7250dbfdf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Абульев С. В.'])[1]/following::p[5]</value>
      <webElementGuid>33f3053e-46ee-4748-bca7-23574ff74840</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Доктор А. М.'])[1]/preceding::p[2]</value>
      <webElementGuid>f3c7c7cd-769b-4552-99c6-b145f257f556</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Доктор П. П.'])[1]/preceding::p[3]</value>
      <webElementGuid>33c88154-3489-43c9-bf77-a9f0e0f12e4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Create P. Т.']/parent::*</value>
      <webElementGuid>59be78fc-c57d-46b4-81ee-6c6e9e79d979</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/p</value>
      <webElementGuid>72c2f815-9a9e-4ee8-aa4a-ed5b53b9f092</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Create P. Т.' or . = 'Create P. Т.')]</value>
      <webElementGuid>ecb62e94-3788-4383-b308-bc860f857eef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
