<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tab_naznachit</name>
   <tag></tag>
   <elementGuidId>a2d85cb9-38c0-4c29-ac71-ced8c3aef415</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.ant-btn.ant-btn-primary.ant-btn-lg.styles_button__3pqej.styles_large__1J0A5.styles_primary__2Afkd.styles_button__1OfyD > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[(text() = 'Назначить' or . = 'Назначить')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>73cdc90a-9eeb-4607-92bb-279c934ce30a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Назначить</value>
      <webElementGuid>9398dbbb-b6c1-4188-8dca-f968935a27bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;drawer&quot;)/div[@class=&quot;styles_wrapper__3fhNR&quot;]/div[@class=&quot;styles_wrapper__background__i5gz- styles_wrapper__background_active__1WfBI&quot;]/div[@class=&quot;styles_wrapper__content__3_KkI styles_wrapper__content_active__3cggn&quot;]/form[@class=&quot;styles_container__2kCJE&quot;]/div[@class=&quot;actions__container&quot;]/div[@class=&quot;styles_actions__3Oxx_&quot;]/button[@class=&quot;ant-btn ant-btn-primary ant-btn-lg styles_button__3pqej styles_large__1J0A5 styles_primary__2Afkd styles_button__1OfyD&quot;]/span[1]</value>
      <webElementGuid>f7f30930-1731-4e5b-a5eb-4fcff24106b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='drawer']/div/div/div/form/div[2]/div/button/span</value>
      <webElementGuid>b2e590e1-1c10-420b-8498-1a8209ce6fd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Подтвержден'])[1]/following::span[2]</value>
      <webElementGuid>a967fd1d-28d2-4aa4-9acc-827f6b4a54cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Добавить услугу'])[1]/following::span[4]</value>
      <webElementGuid>45b44c74-43ad-4749-bf7e-7990ad4ae430</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Назначить']/parent::*</value>
      <webElementGuid>a7964036-518d-4814-8188-5f860eb9367f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span</value>
      <webElementGuid>da375c49-a151-46e0-800c-3da2f1af6869</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Назначить' or . = 'Назначить')]</value>
      <webElementGuid>3c07c652-7229-4960-93b7-75547a81933f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
