<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verif_familia_</name>
   <tag></tag>
   <elementGuidId>8451d352-dfaa-4653-b5a8-08a4a56541f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[3]/div/div/div/form/div[1]/div[1]/div/div[1]/div/label/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#MFow-bw7yx1xK7ir7ntHS</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[(text() = 'Create' or . = 'Create')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bce3a5d9-1bdc-4c53-af05-ceb6e62b67a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MFow-bw7yx1xK7ir7ntHS</value>
      <webElementGuid>2c7b635c-c7d6-4537-bb4d-572996033c16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_input__Xf-yT</value>
      <webElementGuid>7efd1215-f62c-4d24-905d-99201fe04d4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7188fa8d-ed95-4f7e-96da-e5f47424b60c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>dd180de9-971c-44e3-b3dc-a234697b9860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MFow-bw7yx1xK7ir7ntHS&quot;)</value>
      <webElementGuid>7a680c97-52e0-4a9e-9314-b3ea6751b58a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create</value>
      <webElementGuid>c89b909d-f224-4f9b-9f15-5b40f3632768</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='MFow-bw7yx1xK7ir7ntHS']</value>
      <webElementGuid>5b536c78-0ac3-4f91-b370-45639fc51614</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='drawer']/div/div/div/form/div/div/div/div/label/input</value>
      <webElementGuid>6e878770-2348-4692-856a-4e1fbc16526b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>2e287baf-cf9b-499a-8498-7bc7e5f7a409</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'MFow-bw7yx1xK7ir7ntHS']</value>
      <webElementGuid>ee23d8cf-8f93-434e-9eb6-89fb10d9fd27</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
