<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_2022</name>
   <tag></tag>
   <elementGuidId>2eb7b6ff-709b-4321-8a35-5c04a2332a07</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div[2]/main/section/div/form/div/div[2]/div[2]/div/div/div/span/div/div/div[1]/button[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.react-calendar__navigation__label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4388902c-0a5e-41d7-b887-26bb171b4bdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>react-calendar__navigation__label</value>
      <webElementGuid>33f43427-e458-4c26-9563-aedd46160c89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>47f1975f-c0dc-4887-9690-2efb19ed3901</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>август 2022 г.</value>
      <webElementGuid>1b26f99b-0e82-483c-81ab-7793933ac2c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;styles_layout__wrapper__2zeB1&quot;]/div[@class=&quot;styles_layout__container__3D3Vr styles_layout__container_admin__2X_qx&quot;]/main[@class=&quot;styles_layout__content__1BAJN styles_layout__content_admin__WVT00&quot;]/section[@class=&quot;styles_contentLayout__1rqiW&quot;]/div[1]/form[@class=&quot;styles_container__2eYAL&quot;]/div[@class=&quot;styles_container__fields__1O2q5&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;fields&quot;]/div[@class=&quot;styles_container-fields__2EqXi&quot;]/div[@class=&quot;styles_container__4Xrq- styles_container-datePicker__giDll&quot;]/div[@class=&quot;react-date-picker react-date-picker--open react-date-picker--enabled custom_input_3j23dLnd2u9 custom_input_3j2wKdn3   day_width_3fn123d213dg month_width_3fn12s13dg styles_custom-datepicker__Ick84&quot;]/span[1]/div[@class=&quot;react-date-picker__calendar react-date-picker__calendar--open&quot;]/div[@class=&quot;react-calendar styles_custom_calendar__3Kusz&quot;]/div[@class=&quot;react-calendar__navigation&quot;]/button[@class=&quot;react-calendar__navigation__label&quot;]</value>
      <webElementGuid>e2ee9bba-cada-4d66-858b-24e7aa6bd0c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[7]</value>
      <webElementGuid>e79dd924-29d4-40eb-aa84-2c166b5762da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/main/section/div/form/div/div/div[2]/div[2]/div/div/span/div/div/div/button[3]</value>
      <webElementGuid>c685d72e-3b6c-499d-95e7-22a3031a002c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='‹'])[1]/following::button[1]</value>
      <webElementGuid>e7064164-4960-442c-bb6b-0d7ea2a0c36b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='«'])[1]/following::button[2]</value>
      <webElementGuid>70e125fe-731b-4ca5-849a-ec79957221c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='›'])[1]/preceding::button[1]</value>
      <webElementGuid>414e9294-fdd3-41a9-91e1-75030287f2a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]</value>
      <webElementGuid>b284486b-0277-4e96-814b-7065afca5576</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'август 2022 г.' or . = 'август 2022 г.')]</value>
      <webElementGuid>0ad5a5d6-346f-428e-8ea6-a7a3fc68a60f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
