<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__kem vidan</name>
   <tag></tag>
   <elementGuidId>7976f519-a924-47ed-b888-f5dc22edd99c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div[2]/main/section/div/form/div/div[2]/div[2]/div/div[3]/label/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#brmGkaJAeu3TtK-uMCGSX</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d0d5d5fe-90ff-46d0-92fc-af235b90a2dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>brmGkaJAeu3TtK-uMCGSX</value>
      <webElementGuid>c71fa298-323f-48c0-b5dd-16ff14ae3283</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_input__Xf-yT styles_field-organization__2WAp1</value>
      <webElementGuid>7b16a63d-8c07-46bd-bb86-063ebf9ec513</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1f905ede-83f9-4cb4-8b68-d20d7bbb76a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;brmGkaJAeu3TtK-uMCGSX&quot;)</value>
      <webElementGuid>68fcf576-b81d-4ad9-b389-e0cf9d15b7f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='brmGkaJAeu3TtK-uMCGSX']</value>
      <webElementGuid>9cd8a38e-8b4e-454a-a7d1-8175943f2fc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/main/section/div/form/div/div[2]/div[2]/div/label[2]/input</value>
      <webElementGuid>cb68e6dd-a64c-499d-99d1-b90def75ace1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]/input</value>
      <webElementGuid>6dad6e16-4fa5-4ba2-b5ae-c2f3b2f16a63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'brmGkaJAeu3TtK-uMCGSX']</value>
      <webElementGuid>88cae832-b138-4cc6-83d9-8a6b99843c4a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
