<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_pasport_seria_i_number</name>
   <tag></tag>
   <elementGuidId>7ee48b4e-4931-40c4-a47c-fdb1891bd728</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div[2]/main/section/div/form/div/div[2]/div[2]/div/div[1]/label/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#6HFMo3EWkVmlBxTnLGmNx</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b6e889ab-80a4-4fc7-8aad-04a052445b8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>6HFMo3EWkVmlBxTnLGmNx</value>
      <webElementGuid>86971391-404c-440a-bbeb-2122427cac10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_input__Xf-yT field-passport</value>
      <webElementGuid>8f8f6478-ff20-4380-82d5-27a178dd8624</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>b548aefa-c97f-4210-9dc3-f423ec1f57db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>30be26ef-4203-4afb-951a-0a185c67e30c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;6HFMo3EWkVmlBxTnLGmNx&quot;)</value>
      <webElementGuid>87754884-548a-4c78-ac5f-95833d04c57a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='6HFMo3EWkVmlBxTnLGmNx']</value>
      <webElementGuid>ec067959-2959-49c6-9b34-8fca48ded80e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/main/section/div/form/div/div[2]/div[2]/div/label/input</value>
      <webElementGuid>5a06e3cc-6598-40a5-8785-d76fd791d951</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/label/input</value>
      <webElementGuid>05c6629c-282c-4224-9dbe-339e77928f0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '6HFMo3EWkVmlBxTnLGmNx' and @type = 'number']</value>
      <webElementGuid>9f97b9b6-4f61-4df4-bf36-8f7fd861ec85</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
