<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__amb_cart</name>
   <tag></tag>
   <elementGuidId>271680d5-f312-413c-b855-442f484e527e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div[2]/main/section/div/form/div/div[4]/div[2]/div/div/label/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#vqFEt6qYVZ8Ar5Qw5tciR</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d27350c9-a3dd-4745-8d56-0fc9fcd2dc1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vqFEt6qYVZ8Ar5Qw5tciR</value>
      <webElementGuid>470171ee-30ec-4351-a3c3-deada7f0e89a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_input__Xf-yT field</value>
      <webElementGuid>397e30d7-fcd9-43b7-9b00-d1d742c9273a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>93eae4dd-d1df-4845-ad5b-73a8d60b8454</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vqFEt6qYVZ8Ar5Qw5tciR&quot;)</value>
      <webElementGuid>7c720ba5-4fce-420f-87fa-77be5a868cfc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='vqFEt6qYVZ8Ar5Qw5tciR']</value>
      <webElementGuid>6f6d76f2-88b7-4834-992f-4d25a063997d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/main/section/div/form/div/div[4]/div[2]/div/label/input</value>
      <webElementGuid>3d54db34-2062-4deb-afb6-06258589beb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/label/input</value>
      <webElementGuid>e6490914-8182-4306-aaf6-53c27b505fbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'vqFEt6qYVZ8Ar5Qw5tciR']</value>
      <webElementGuid>0624c86a-e346-4dfd-a226-e0365c575744</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
