<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_comment</name>
   <tag></tag>
   <elementGuidId>97105016-7f68-4bdf-a8bb-80e39172ce05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div[2]/main/section/div/form/div/div[5]/div[2]/div/div/textarea</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Uf7oMfHCetwiTdnLG-KR6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>4a192c60-c9ec-4ee5-a559-7caec074004b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>7de75130-cb53-465c-a945-6612e1d95f5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Uf7oMfHCetwiTdnLG-KR6</value>
      <webElementGuid>1fb080d4-51c4-4f76-b0a0-bc9233145f55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5a268a84-ce35-4b4a-bb54-34fdb5004620</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input styles_textarea__3FuFL</value>
      <webElementGuid>8b8813dc-040c-4d94-b5b0-5abb6ecbe0ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Тест регресс</value>
      <webElementGuid>8cf69b46-e591-4486-afcd-8aa8e2774247</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Uf7oMfHCetwiTdnLG-KR6&quot;)</value>
      <webElementGuid>8d3b341a-3ea2-4725-abaf-f9f84a53b673</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='Uf7oMfHCetwiTdnLG-KR6']</value>
      <webElementGuid>f81c91ff-265c-49a6-892e-1c7149f4d733</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/main/section/div/form/div/div[5]/div[2]/div/div/textarea</value>
      <webElementGuid>dda45624-6433-4071-aa11-4312300ccdb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='КОММЕНТАРИЙ'])[1]/following::textarea[1]</value>
      <webElementGuid>2992680d-35d1-463a-88d3-e9927c7dfd75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Номер амбулаторной карты'])[1]/following::textarea[1]</value>
      <webElementGuid>3f9ed802-0af0-4f4d-b612-65bcf3cd60a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Комментарий о пациенте (в свободной форме)'])[1]/preceding::textarea[1]</value>
      <webElementGuid>920c2524-ab6c-4278-98cf-4cae730bf5d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Зарегистрировать'])[1]/preceding::textarea[1]</value>
      <webElementGuid>44d41915-fd6f-44f2-8cb2-8b5064923af1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Тест регресс']/parent::*</value>
      <webElementGuid>a220208e-5f6b-414a-bfa0-9451d663b3ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>4ce7fb98-5716-4f95-9356-69c4a92b8e6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'Uf7oMfHCetwiTdnLG-KR6' and (text() = 'Тест регресс' or . = 'Тест регресс')]</value>
      <webElementGuid>28f91092-26c9-4249-9ad5-a0b5b0e9a19a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
