<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__city</name>
   <tag></tag>
   <elementGuidId>8893adce-138d-4d05-a3cf-9a364ab57f40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div[2]/main/section/div/form/div/div[3]/div[2]/div/div[2]/label/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#vEoVYtH-yAW31PEK5KOiV</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e1aa5198-6d40-40ee-8ba4-3782b636e86e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vEoVYtH-yAW31PEK5KOiV</value>
      <webElementGuid>2db9a3f2-4a0c-439e-bece-7f52fe0a6cc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_input__Xf-yT field</value>
      <webElementGuid>01b3f769-f30d-4cb5-abf2-899f5cc4076b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e551695b-afdd-4e59-a71c-e830b2c9800f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vEoVYtH-yAW31PEK5KOiV&quot;)</value>
      <webElementGuid>a83a10e1-a39c-4e45-85a0-abb593d77eaa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='vEoVYtH-yAW31PEK5KOiV']</value>
      <webElementGuid>bc46f070-af0b-4b3a-83d3-ae86d5e61996</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/main/section/div/form/div/div[3]/div[2]/div/label[2]/input</value>
      <webElementGuid>04253c69-dace-4111-992e-565ae33d69c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/label[2]/input</value>
      <webElementGuid>93be64ac-13d6-48ff-b3d1-e753a2bfab56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'vEoVYtH-yAW31PEK5KOiV']</value>
      <webElementGuid>76c6860a-9f00-4e47-8429-5d0a7eb97af1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
