<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__country</name>
   <tag></tag>
   <elementGuidId>b77d1b5c-ce26-4d14-b69a-8e76a87b536d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div[2]/main/section/div/form/div/div[3]/div[2]/div/div[1]/label/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#yOqccnNrpActmAjRIUYEv</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d934286a-d045-4520-b673-795acc487284</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>yOqccnNrpActmAjRIUYEv</value>
      <webElementGuid>707c33f9-94b4-48e5-9728-f695c75ec952</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_input__Xf-yT field</value>
      <webElementGuid>e32ef7ca-c9ca-455f-834f-668bac343c25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4b05a556-5112-48be-b05d-a016edc6157b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Р</value>
      <webElementGuid>57c29fc9-2518-4116-8019-6f2eddd00118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yOqccnNrpActmAjRIUYEv&quot;)</value>
      <webElementGuid>f1fb85e5-d56c-4229-b02c-a40dcf57307f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='yOqccnNrpActmAjRIUYEv']</value>
      <webElementGuid>71d70df6-3552-44ce-bf32-12b3ed5c72ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/main/section/div/form/div/div[3]/div[2]/div/label/input</value>
      <webElementGuid>c7f925b2-0f33-40dc-a1e0-d9cf09e8d5ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/label/input</value>
      <webElementGuid>db22da6d-53a1-49cc-b64f-bb4cb6b01d93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'yOqccnNrpActmAjRIUYEv']</value>
      <webElementGuid>3bf04f7e-d8d6-4c28-bc13-b7bbf7933f01</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
