<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Name</name>
   <tag></tag>
   <elementGuidId>61f339a2-8583-4218-b75d-6fb94c5aa523</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div[2]/main/section/div/form/div/div[1]/div[2]/div[1]/div[2]/div/label/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#yMyjvil-vHLi50gPgzl8k</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5d663ba1-8d72-4f4d-861d-a33b2f49b09e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>yMyjvil-vHLi50gPgzl8k</value>
      <webElementGuid>3e574e07-30bd-4f82-b091-bc397bcf9035</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_input__Xf-yT styles_field__3HGRG</value>
      <webElementGuid>ca80683d-d0b8-420a-b2da-adb87e2fbe87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6c2d7884-b6f4-4a1e-9541-5d3ff1642dab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Q</value>
      <webElementGuid>9bea0676-9bf5-4e5d-a958-05316cae9dfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yMyjvil-vHLi50gPgzl8k&quot;)</value>
      <webElementGuid>0404c370-0285-4429-a937-414fb255b4ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='yMyjvil-vHLi50gPgzl8k']</value>
      <webElementGuid>3c5e23f6-7921-4bd0-8cf4-bb52acd24636</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/main/section/div/form/div/div/div[2]/div/div[2]/label/input</value>
      <webElementGuid>7a2add15-331c-40a7-8777-9320bb563fc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/label/input</value>
      <webElementGuid>68acc310-544c-4bf1-8400-ab1cd811a929</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'yMyjvil-vHLi50gPgzl8k']</value>
      <webElementGuid>b304e5d3-4dd9-42f4-9441-e6ce4eb2084d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
