<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Familia</name>
   <tag></tag>
   <elementGuidId>9c41b218-a2d1-4cb0-b765-22e3c5bca116</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div[2]/main/section/div/form/div/div[1]/div[2]/div[1]/div[1]/div/label/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ShYpVQpumUCXCe_TnC44m</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9d1f6be1-fc57-4fce-ad75-01ffaf445673</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ShYpVQpumUCXCe_TnC44m</value>
      <webElementGuid>18f8433f-9f20-499f-9b7c-ee082ddfb349</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_input__Xf-yT styles_field__3HGRG</value>
      <webElementGuid>f812034c-b85f-4714-9da7-595b1a5895c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>20025f8b-f649-40f9-a8e8-b137d634498d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ShYpVQpumUCXCe_TnC44m&quot;)</value>
      <webElementGuid>b1dacf9b-9c3c-4cd8-8c7f-bc96b47caf8f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ShYpVQpumUCXCe_TnC44m']</value>
      <webElementGuid>91ad6fbd-6384-47f2-bdac-9e4f22210750</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/main/section/div/form/div/div/div[2]/div/div/label/input</value>
      <webElementGuid>14a18acd-797e-4d29-a754-29b38b71173c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>bd88049f-8535-4b03-89a9-1d66e2ff46f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ShYpVQpumUCXCe_TnC44m']</value>
      <webElementGuid>0fad04b9-4adc-42d3-baff-7dcd1a44c06c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
