<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Otchestvo</name>
   <tag></tag>
   <elementGuidId>9ee81a4a-fcff-4a54-81a1-ea15e10c2887</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div[2]/main/section/div/form/div/div[1]/div[2]/div[1]/div[3]/div/label/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#7LWAN9YRGUKDNXwJZsssJ</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>21093558-e464-4f63-879e-e6ed8180bc25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>7LWAN9YRGUKDNXwJZsssJ</value>
      <webElementGuid>87aaf428-acd2-4902-b6e3-61e155d896cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_input__Xf-yT styles_field__3HGRG</value>
      <webElementGuid>7d390a09-b1d8-4325-87b4-37abc9cf347f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c5266ead-0cb4-4f29-93b8-c82e75148144</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>r</value>
      <webElementGuid>d8f63d51-106b-4333-a133-2e3c639a3219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;7LWAN9YRGUKDNXwJZsssJ&quot;)</value>
      <webElementGuid>e6e98e92-908b-4978-95aa-e949a80fe00d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='7LWAN9YRGUKDNXwJZsssJ']</value>
      <webElementGuid>bf4fc9da-4d2c-481d-8df4-385c64aa3ef0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/main/section/div/form/div/div/div[2]/div/div[3]/label/input</value>
      <webElementGuid>24e6a5d4-a936-4212-b955-fe2c519e3342</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/label/input</value>
      <webElementGuid>09538ac3-7496-4353-9cee-94870c09b866</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '7LWAN9YRGUKDNXwJZsssJ']</value>
      <webElementGuid>120afe04-8c44-46b3-872c-eb2fae8f3b42</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
