<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__address</name>
   <tag></tag>
   <elementGuidId>4b68a048-12dd-408e-ab4f-1aa9db53775b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div[2]/main/section/div/form/div/div[3]/div[2]/div/div[3]/label/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#TgOOstjS8wXwwss5M9WZH</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d9e2bb59-88fa-4a09-b5cb-645bd96fa2a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TgOOstjS8wXwwss5M9WZH</value>
      <webElementGuid>3323e096-009e-4634-a887-b1f2e3d2d8c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_input__Xf-yT styles_field-address__1kVlG</value>
      <webElementGuid>6704615c-a364-4df5-9279-5762f7fb473d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>362d2d94-51bc-4aba-bd93-f43dd1e31195</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TgOOstjS8wXwwss5M9WZH&quot;)</value>
      <webElementGuid>8b23ce2b-4be8-488e-a1ce-b62f064dbcdb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TgOOstjS8wXwwss5M9WZH']</value>
      <webElementGuid>e00f47ce-2810-4022-9fe8-7139875b84c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/main/section/div/form/div/div[3]/div[2]/div/label[3]/input</value>
      <webElementGuid>fb249e13-e3eb-4065-96d8-99e403830a90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[3]/input</value>
      <webElementGuid>0614834a-483d-4b2a-a22b-e86e7963a65e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'TgOOstjS8wXwwss5M9WZH']</value>
      <webElementGuid>a156ebbc-fea2-498d-b127-27b963c474cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
