<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>profile_vrach_in_page_vrach_kliniki</name>
   <tag></tag>
   <elementGuidId>a82873b0-b400-4773-b668-dd9626c5f964</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/main/section/div/div[3]/div[2]/span/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.ant-popover-open</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '${GlobalVariable.Test_vrach_full}' or . = '${GlobalVariable.Test_vrach_full}')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ce855dfa-bee0-4032-a5bc-af6558855123</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-popover-open</value>
      <webElementGuid>e8fe60de-812e-457f-9874-6ee2d6cc5d15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>${GlobalVariable.Test_vrach_full}</value>
      <webElementGuid>5f89a71e-8c13-4f55-9ca1-ca8d32602377</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;styles_layout__wrapper__2zeB1&quot;]/div[@class=&quot;styles_layout__container__3D3Vr styles_layout__container_admin__2X_qx&quot;]/main[@class=&quot;styles_layout__content__1BAJN styles_layout__content_admin__WVT00&quot;]/section[@class=&quot;styles_contentLayout__1rqiW&quot;]/div[@class=&quot;styles_container__1PndP&quot;]/div[@class=&quot;styles_table__wrapper__3VcQm&quot;]/div[@class=&quot;styles_table__row__5Gwmm&quot;]/span[@class=&quot;styles_table__row__item-shortened__1yU3K&quot;]/a[1]/span[@class=&quot;ant-popover-open&quot;]</value>
      <webElementGuid>e61efa0c-5c81-4dce-9102-e449e492dbd8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/main/section/div/div[3]/div[2]/span/a/span</value>
      <webElementGuid>7ba4ef1a-9ec7-48b3-8b5e-886a0d8fa659</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Статус'])[1]/following::span[2]</value>
      <webElementGuid>2d83c61d-962d-4a2b-a50d-22f2486c1d4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Контактные данные'])[1]/following::span[3]</value>
      <webElementGuid>a57dd424-5121-4b49-9044-3359347d6bfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Акушер-гинеколог'])[1]/preceding::span[1]</value>
      <webElementGuid>43331a85-63bb-4f6f-8715-506ad1345e90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Андролог'])[1]/preceding::span[2]</value>
      <webElementGuid>7d1015cb-0c40-446b-97d5-cf09395fd085</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Боевая Машина Магович']/parent::*</value>
      <webElementGuid>4ab00996-fa55-4cbc-b9e0-da5b9d95cf39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/a/span</value>
      <webElementGuid>682e14f0-c3c4-407f-8013-d4567065539f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Боевая Машина Магович' or . = 'Боевая Машина Магович')]</value>
      <webElementGuid>ce42ec24-ce5b-4067-90d8-2621308dfe4d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
